---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: clusterstorage
stringData:
  # 通过ceph auth get client.admin查看
  userID: admin 
  userKey: AQAZYdJd6UnhIxAAeFPD0RR8+fSj5n6LffYXaQ== 

  # Required for dynamically provisioned volumes
  adminID: admin
  adminKey: AQAZYdJd6UnhIxAAeFPD0RR8+fSj5n6LffYXaQ==
