{
 "title": "Analysis by Pod",
 "description": "Part 3 of 3 dashboards to help you visualise your kubernetes costs.",
 "tags": [
  "cost",
  "utilisation",
  "metrics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "costcpu", "label": "CPU", "query": "${VAR_COSTCPU}" },
   { "name": "costpcpu", "label": "PE CPU", "query": "${VAR_COSTPCPU}" },
   { "name": "costram", "label": "RAM", "query": "${VAR_COSTRAM}" },
   { "name": "costpram", "label": "PE RAM", "query": "${VAR_COSTPRAM}" },
   { "name": "costStorageStandard", "label": "Storage", "query": "${VAR_COSTSTORAGESTANDARD}" },
   { "name": "costStorageSSD", "label": "SSD", "query": "${VAR_COSTSTORAGESSD}" },
   { "name": "costDiscount", "label": "Disc.", "query": "${VAR_COSTDISCOUNT}" },
   {
    "name": "namespace",
    "label": "NS",
    "query": "query_result(sum(container_memory_working_set_bytes{namespace!=\"\"}) by (namespace))"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "query_result(sum(container_memory_working_set_bytes{namespace=\"$namespace\"}) by (pod))"
   }
  ]
 },
 "panels": [
  {
   "title": "Container cost and utilisation analysis",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(\n  sum(container_spec_cpu_shares{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",cloud_google_com_gke_preemptible!=\"true\"}/1000*($costcpu - ($costcpu / 100 * $costDiscount))) by(container)\n  or\n  count(\n    count(container_spec_cpu_shares{namespace=\"$namespace\",container!=\"POD\",pod=\"$pod\"}) by(container)\n  ) by(container) -1\n)\n\n+\n\n(\n  sum(container_spec_cpu_shares{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",cloud_google_com_gke_preemptible=\"true\"}/1000*$costpcpu) by(container)\n  or\n  count(\n    count(container_spec_cpu_shares{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\"}) by(container)\n  ) by(container) -1\n)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(\n   count(count(container_spec_cpu_shares{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\"}) by (container)) by (container)  \n   * on (container) \n   sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\"}[1m])) by (container)\n) by (container) * 1000\n/\nsum(container_spec_cpu_shares{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\"}) by (container) * 100",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "(\n  sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",cloud_google_com_gke_preemptible!=\"true\"}/1024/1024/1024*($costram- ($costram / 100 * $costDiscount))) by(container)\n  or\n  count(\n    count(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\"}) by(container)\n  ) by(container) -1\n)\n\n+\n\n(\n  sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",cloud_google_com_gke_preemptible=\"true\"}/1024/1024/1024*$costpram) by(container)\n  or\n  count(\n    count(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\"}) by(container)\n  ) by(container) -1\n)",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum(\n   count(count(container_memory_working_set_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\"}) by (container)) by (container)  \n   * on (container) \n   sum(avg_over_time(container_memory_working_set_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\"}[1m])) by (container)\n) by (container)\n/\nsum(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\"}) by (container) * 100",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "(\n  sum(container_spec_cpu_shares{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",cloud_google_com_gke_preemptible!=\"true\"}/1000*($costcpu - ($costcpu / 100 * $costDiscount))) by(container)\n  or\n  count(\n    count(container_spec_cpu_shares{namespace=\"$namespace\",container!=\"POD\",pod=\"$pod\"}) by(container)\n  ) by(container) -1\n)\n\n+\n\n(\n  sum(container_spec_cpu_shares{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",cloud_google_com_gke_preemptible=\"true\"}/1000*$costpcpu) by(container)\n  or\n  count(\n    count(container_spec_cpu_shares{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\"}) by(container)\n  ) by(container) -1\n)\n\n+\n\n(\n  sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",cloud_google_com_gke_preemptible!=\"true\"}/1024/1024/1024*($costram- ($costram / 100 * $costDiscount))) by(container)\n  or\n  count(\n    count(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\"}) by(container)\n  ) by(container) -1\n)\n\n+\n\n(\n  sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",cloud_google_com_gke_preemptible=\"true\"}/1024/1024/1024*$costpram) by(container)\n  or\n  count(\n    count(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\"}) by(container)\n  ) by(container) -1\n)"
    }
   ]
  },
  {
   "title": "CPU Core Usage vs Requested",
   "type": "graph",
   "description": "This graph attempts to show you CPU use of your application vs its requests",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=\"$pod\", container!=\"POD\"}[1m])) by (container)",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "sum(container_spec_cpu_shares{namespace=~\"$namespace\", pod=\"$pod\", container!=\"POD\"}) by (container) / 1000",
     "legendFormat": "{{ container }} (requested)"
    }
   ]
  },
  {
   "title": "RAM Usage vs Requested",
   "type": "graph",
   "description": "This graph attempts to show you RAM use of your application vs its requests",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (avg_over_time (container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", container!=\"POD\"}[1m])) by (container)",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{namespace=~\"$namespace\", pod=\"$pod\", container!=\"POD\"}) by (container)",
     "legendFormat": "{{ container }} (requested)"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "description": "Traffic in and out of this pod, as a sum of its containers",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[1m])) by (pod)",
     "legendFormat": "<- in"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[1m])) by (pod)",
     "legendFormat": "-> out"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "description": "Disk read writes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_fs_writes_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[1m])) by (pod)",
     "legendFormat": "<- write"
    },
    {
     "expr": "- sum (rate (container_fs_reads_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[1m])) by (pod)",
     "legendFormat": "-> read"
    }
   ]
  }
 ]
}