{
 "title": "Ceph - OSD",
 "description": "CEPH OSD Status.",
 "tags": [
  "ceph",
  "osd"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "osd", "label": "OSD", "query": "label_values(ceph_osd_up, osd)" }
  ]
 },
 "panels": [
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_osd_up{osd=\"$osd\"}"
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_osd_in{osd=\"$osd\"}"
    }
   ]
  },
  {
   "title": "Total OSDs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "ceph_osds" }
   ]
  },
  { "title": "OSD: $osd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "PGs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_pgs{osd=~\"$osd\"}",
     "legendFormat": "Number of PGs - {{ osd }}"
    },
    {
     "expr": "avg(ceph_osd_pgs)",
     "legendFormat": "Average Number of PGs in the Cluster"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_osd_utilization{osd=\"$osd\"}"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_perf_apply_latency_seconds{osd=~\"$osd\"}",
     "legendFormat": "Apply Latency (s) - {{ osd }}"
    },
    {
     "expr": "ceph_osd_perf_commit_latency_seconds{osd=~\"$osd\"}",
     "legendFormat": "Commit Latency (s) - {{ osd }}"
    }
   ]
  },
  {
   "title": "OSD Storage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_avail_bytes{osd=~\"$osd\"}",
     "legendFormat": "Available - {{ osd }}"
    },
    {
     "expr": "ceph_osd_used_bytes{osd=~\"$osd\"}",
     "legendFormat": "Used - {{ osd }}"
    }
   ]
  },
  {
   "title": "Utilization Variance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_variance{osd=~\"$osd\"}",
     "legendFormat": "Available - {{ osd }}"
    }
   ]
  }
 ]
}