#!/bin/sh

# Modify backend forwarding port
sed -i "s/K8S_MASTER_PORT/${K8S_MASTER_PORT}/g" /etc/confd/templates/nginx.tmpl
# Run confd
confd -onetime -backend env

# Start nginx
nginx -g 'daemon off;'
