---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true" # true|false
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.2.220
  share: /apps/data/
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - hard
  - rw,nolock
  - nfsvers=4.1