kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cephfs
provisioner: ceph.com/cephfs
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
    monitors: 10.11.11.2,10.11.11.3,10.11.11.4:6789
    adminId: admin
    adminSecretName: ceph-secret-admin
    adminSecretNamespace: "clusterstorage"
    claimRoot: /kube-volumes
