{
 "title": "Network Details",
 "description": "Network Overview",
 "tags": [
  "Percona",
  "OS"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(node_uname_info,environment)"
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": "label_values(node_uname_info{environment=~\"$env\"}, instance)"
   },
   {
    "name": "device",
    "label": "Device",
    "query": "label_values(node_network_receive_packets_total{instance=~\"$node_name\"},device)"
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_name)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, cluster)"
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
   },
   { "name": "schema", "label": "Schema" }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "Last Hour statistic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Inbound Speed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!=\"lo\",instance=~\"$node_name\"}[1h])) or\nsum(rate(rdsosmetrics_network_rx{instance=~\"$node_name\"}[1h]))"
    }
   ]
  },
  {
   "title": "Outbound Speed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 3 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!=\"lo\",instance=~\"$node_name\"}[1h])) or\nsum(rate(rdsosmetrics_network_tx{instance=~\"$node_name\"}[1h]))"
    }
   ]
  },
  {
   "title": "Traffic Errors and Drops",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_errs_total{instance=~\"$node_name\", device!=\"lo\"}[1h])) +\nsum(increase(node_network_transmit_errs_total{instance=~\"$node_name\", device!=\"lo\"}[1h])) +\nsum(increase(node_network_receive_drop_total{instance=~\"$node_name\", device!=\"lo\"}[1h])) +\nsum(increase(node_network_transmit_drop_total{instance=~\"$node_name\", device!=\"lo\"}[1h]))"
    }
   ]
  },
  {
   "title": "Retransmit rate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (instance) (rate(node_netstat_Tcp_RetransSegs{instance=~\"$node_name\"}[1h]) * 100 / (rate(node_netstat_Tcp_OutSegs{instance=~\"$node_name\"}[1h]) + rate(node_netstat_Tcp_InSegs{instance=~\"$node_name\"}[1h])))"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes", "label": "bits out (-) / bits in (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"$node_name\", device!=\"lo\"}[$interval])) or \nsum(irate(node_network_receive_bytes_total{instance=~\"$node_name\", device!=\"lo\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_rx{instance=~\"$node_name\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_rx{instance=~\"$node_name\"}[5m])) ",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=~\"$node_name\", device!=\"lo\"}[$interval])) or \nsum(irate(node_network_transmit_bytes_total{instance=~\"$node_name\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{instance=~\"$node_name\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_tx{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Network Utilization Hourly",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=~\"$node_name\", device!=\"lo\"}[1h])) or \nsum(increase(rdsosmetrics_network_rx{instance=~\"$node_name\"}[1h]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\"$node_name\", device!=\"lo\"}[1h]))  or \nsum(increase(rdsosmetrics_network_tx{instance=~\"$node_name\"}[1h]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  { "title": "Network traffic details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Network Traffic by Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "avg by (instance,device) (rate(node_network_receive_packets_total{instance=~\"$node_name\", device!=\"lo\"}[$interval]) or \nirate(node_network_receive_packets_total{instance=~\"$node_name\", device!=\"lo\"}[5m]))",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "avg by (instance,device) (rate(node_network_transmit_packets_total{instance=~\"$node_name\", device!=\"lo\"}[$interval]) or \nirate(node_network_transmit_packets_total{instance=~\"$node_name\", device!=\"lo\"}[5m]))",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance,device) (rate(node_network_receive_errs_total{instance=~\"$node_name\", device!=\"lo\"}[$interval]) or \nirate(node_network_receive_errs_total{instance=~\"$node_name\", device!=\"lo\"}[5m]))",
     "legendFormat": "{{device}} - Receive errors"
    },
    {
     "expr": "avg by (instance,device) (rate(node_network_transmit_errs_total{instance=~\"$node_name\", device!=\"lo\"}[$interval]) or\nirate(node_network_transmit_errs_total{instance=~\"$node_name\", device!=\"lo\"}[5m]))",
     "legendFormat": "{{device}} - Transmit errors"
    }
   ]
  },
  {
   "title": "Network Traffic Drop",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance,device) (rate(node_network_receive_drop_total{instance=~\"$node_name\", device!=\"lo\"}[$interval]) or\nirate(node_network_receive_drop_total{instance=~\"$node_name\", device!=\"lo\"}[5m]))",
     "legendFormat": "{{device}} - Receive drop"
    },
    {
     "expr": "avg by (instance,device) (rate(node_network_transmit_drop_total{instance=~\"$node_name\", device!=\"lo\"}[$interval]) or \nirate(node_network_transmit_drop_total{instance=~\"$node_name\", device!=\"lo\"}[5m]))",
     "legendFormat": "{{device}} - Transmit drop"
    }
   ]
  },
  {
   "title": "Network Traffic Multicast",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "avg by (instance,device) (rate(node_network_receive_multicast_total{instance=~\"$node_name\", device!=\"lo\"}[$interval]) or\nirate(node_network_receive_multicast_total{instance=~\"$node_name\", device!=\"lo\"}[5m]))",
     "legendFormat": "{{device}} - Receive multicast"
    },
    {
     "expr": "avg by (instance,device) (rate(node_network_transmit_multicast_total{instance=~\"$node_name\", device!=\"lo\"}[$interval]) or\nirate(node_network_transmit_multicast_total{instance=~\"$node_name\", device!=\"lo\"}[5m]))",
     "legendFormat": "{{device}} - Transmit multicast"
    }
   ]
  },
  {
   "title": "Network Netstat TCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "The algorithm used to determine the timeout value",
     "type": "singlestat",
     "description": "The algorithm used to determine the timeout value used for retransmitting unacknowledged octets.\n\nother  - none of the following\n\nconstant - a constant rto\n\nrsre - MIL-STD-1778, Appendix B\n\nvanj - Van Jacobson's algorithm\n\nrfc2988  - RFC 2988",
     "gridPos": { "h": 2, "w": 8, "x": 0, "y": 36 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (instance) (node_netstat_Tcp_RtoAlgorithm{instance=~\"$node_name\"})"
      }
     ]
    },
    {
     "title": "Min TCP Retransmission timeout",
     "type": "singlestat",
     "description": "The minimum value permitted by a TCP implementation for  the retransmission timeout, measured in milliseconds.\nMore refined semantics for objects of this type depend on the algorithm used to determine the retransmission timeout; in particular, the IETF standard algorithm rfc2988(5) provides a minimum value.\"",
     "gridPos": { "h": 2, "w": 8, "x": 8, "y": 36 },
     "format": "ms",
     "valueName": "min",
     "targets": [
      {
       "expr": "avg by (instance) (min_over_time(node_netstat_Tcp_RtoMin{instance=~\"$node_name\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Max TCP Retransmission timeout",
     "type": "singlestat",
     "description": "The maximum value permitted by a TCP implementation for the retransmission timeout, measured in milliseconds.\nMore refined semantics for objects of this type depend on the algorithm used to determine the retransmission timeout; in particular, the IETF standard algorithm rfc2988(5) provides an upper bound (as part of an adaptive backoff algorithm).\"",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 36 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (instance) (max_over_time(node_netstat_Tcp_RtoMax{instance=~\"$node_name\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Netstat: TCP",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_netstat_Tcp_CurrEstab{instance=~\"$node_name\"}[$interval]) or\nmax_over_time(node_netstat_Tcp_CurrEstab{instance=~\"$node_name\"}[5m])",
       "legendFormat": "established"
      },
      {
       "expr": "max_over_time(node_netstat_Tcp_ActiveOpens{instance=~\"$node_name\"}[$interval]) or\nmax_over_time(node_netstat_Tcp_ActiveOpens{instance=~\"$node_name\"}[5m])",
       "legendFormat": "activeOpens"
      },
      {
       "expr": "max_over_time(node_netstat_Tcp_PassiveOpens{instance=~\"$node_name\"}[$interval]) or\nmax_over_time(node_netstat_Tcp_PassiveOpens{instance=~\"$node_name\"}[5m])",
       "legendFormat": "passiveOpens"
      },
      {
       "expr": "max_over_time(node_netstat_Tcp_EstabResets{instance=~\"$node_name\"}[$interval]) or\nmax_over_time(node_netstat_Tcp_EstabResets{instance=~\"$node_name\"}[5m])",
       "legendFormat": "estabResets"
      },
      {
       "expr": "max_over_time(node_netstat_Tcp_AttemptFails{instance=~\"$node_name\"}[$interval]) or\nmax_over_time(node_netstat_Tcp_AttemptFails{instance=~\"$node_name\"}[5m])",
       "legendFormat": "attemptfails"
      },
      {
       "expr": "max_over_time(node_netstat_Tcp_RetransSegs{instance=~\"$node_name\"}[$interval]) or\nmax_over_time(node_netstat_Tcp_RetransSegs{instance=~\"$node_name\"}[5m])",
       "legendFormat": "retransSegs"
      }
     ]
    },
    {
     "title": "TCP Segments",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short", "label": "Out (-) / In (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_InCsumErrors{instance=~\"$node_name\"}[$interval]) or irate(node_netstat_Tcp_InCsumErrors{instance=~\"$node_name\"}[5m])",
       "legendFormat": "InCsumErrors"
      },
      {
       "expr": "rate(node_netstat_Tcp_InErrs{instance=~\"$node_name\"}[$interval]) or irate(node_netstat_Tcp_InErrs{instance=~\"$node_name\"}[5m])",
       "legendFormat": "InErrs "
      },
      {
       "expr": "rate(node_netstat_Tcp_InSegs{instance=~\"$node_name\"}[$interval]) or irate(node_netstat_Tcp_InSegs{instance=~\"$node_name\"}[5m])",
       "legendFormat": "InSegs"
      },
      {
       "expr": "rate(node_netstat_Tcp_OutRsts{instance=~\"$node_name\"}[$interval]) or irate(node_netstat_Tcp_OutRsts{instance=~\"$node_name\"}[5m])",
       "legendFormat": "OutRsts"
      },
      {
       "expr": "rate(node_netstat_Tcp_OutSegs{instance=~\"$node_name\"}[$interval]) or irate(node_netstat_Tcp_OutSegs{instance=~\"$node_name\"}[5m])",
       "legendFormat": "OutSegs"
      },
      {
       "expr": "rate(node_netstat_Tcp_RetransSegs{instance=~\"$node_name\"}[$interval]) or irate(node_netstat_Tcp_RetransSegs{instance=~\"$node_name\"}[5m])",
       "legendFormat": "RetransSegs"
      }
     ]
    }
   ]
  },
  { "title": "Network Netstat UDP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Netstat: UDP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Out (-) / In (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_netstat_Udp_InDatagrams{instance=~\"$node_name\"}[$interval]) or irate(node_netstat_Udp_InDatagrams{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Udp_InDatagrams"
    },
    {
     "expr": "sum(rate(node_netstat_Udp_InErrors{instance=~\"$node_name\"}[$interval]) or irate(node_netstat_Udp_InErrors{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Udp_InErrors"
    },
    {
     "expr": "sum(rate(node_netstat_Udp_OutDatagrams{instance=~\"$node_name\"}[$interval]) or irate(node_netstat_Udp_OutDatagrams{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Udp_OutDatagrams"
    },
    {
     "expr": "sum(rate(node_netstat_Udp_NoPorts{instance=~\"$node_name\"}[$interval]) or irate(node_netstat_Udp_NoPorts{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Udp_NoPorts"
    },
    {
     "expr": "sum(rate(node_netstat_Udp_InCsumErrors{instance=~\"$node_name\"}[$interval]) or irate(node_netstat_Udp_InCsumErrors{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Udp_InCsumErrors"
    },
    {
     "expr": "sum(rate(node_netstat_Udp_RcvbufErrors{instance=~\"$node_name\"}[$interval]) or irate(node_netstat_Udp_RcvbufErrors{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Udp_RcvbufErrors"
    },
    {
     "expr": "sum(rate(node_netstat_Udp_SndbufErrors{instance=~\"$node\"}[$interval]) or irate(node_netstat_Udp_SndbufErrors{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Udp_SndbufErrors"
    }
   ]
  },
  {
   "title": "UDP Lite",
   "type": "graph",
   "description": "**InDatagrams** Packets received\n\n**OutDatagrams** Packets sent\n\n**InCsumErrors** Datagrams with checksum errors\n\n**InErrors** Datagrams that could not be delivered to an application\n\n**RcvbufErrors** Datagrams for which not enough socket buffer memory to receive\n\n**SndbufErrors**  Datagrams for which not enough socket buffer memory to transmit\n\n**NoPorts**  Datagrams received on a port with no listener",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ops", "label": "Out (-) / In (+)" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (rate(node_netstat_UdpLite_InDatagrams{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_UdpLite_InDatagrams{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "InDatagrams "
    },
    {
     "expr": "avg by (instance) (rate(node_netstat_UdpLite_OutDatagrams{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_UdpLite_OutDatagrams{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "OutDatagrams "
    },
    {
     "expr": "avg by (instance) (rate(node_netstat_UdpLite_InCsumErrors{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_UdpLite_InCsumErrors{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "InCsumErrors"
    },
    {
     "expr": "avg by (instance) (rate(node_netstat_UdpLite_InErrors{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_UdpLite_InErrors{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "InErrors "
    },
    {
     "expr": "avg by (instance) (rate(node_netstat_UdpLite_RcvbufErrors{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_UdpLite_RcvbufErrors{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "RcvbufErrors "
    },
    {
     "expr": "avg by (instance) (rate(node_netstat_UdpLite_SndbufErrors{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_UdpLite_SndbufErrors{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "SndbufErrors "
    },
    {
     "expr": "avg by (instance) (rate(node_netstat_UdpLite_NoPorts{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_UdpLite_NoPorts{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "NoPorts"
    }
   ]
  },
  {
   "title": "ICMP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "ICMP Errors",
     "type": "graph",
     "description": "**InErrors**  Messages which the entity received but determined as having ICMP-specific errors (bad ICMP checksums, bad length, etc.)\n\n**OutErrors** Messages which this entity did not send due to problems discovered within ICMP, such as a lack of buffers\n\n**InDestUnreachs**  Destination Unreachable messages received\n\n**OutDestUnreachs** Destination Unreachable messages sent\n\n**InType3** Destination unreachable\n\n**OutType3** Destination unreachable\n\n**InCsumErrors** Messages with ICMP checksum errors\n\n**InTimeExcds** Time Exceeded messages received",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "ops", "label": "Out (-) / In (+)" }
     ],
     "targets": [
      {
       "expr": "avg by (instance) (rate(node_netstat_Icmp_InErrors{instance=~\"$node_name\"}[$interval]) \nor irate(node_netstat_Icmp_InErrors{instance=~\"$node_name\"}[5m]))",
       "legendFormat": "InErrors"
      },
      {
       "expr": "avg by (instance) (rate(node_netstat_Icmp_OutErrors{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_Icmp_OutErrors{instance=~\"$node_name\"}[5m]))",
       "legendFormat": "OutErrors"
      },
      {
       "expr": "avg by (instance) (rate(node_netstat_Icmp_InDestUnreachs{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_Icmp_InDestUnreachs{instance=~\"$node_name\"}[5m]))",
       "legendFormat": "InDestUnreachs"
      },
      {
       "expr": "avg by (instance) (rate(node_netstat_Icmp_OutDestUnreachs{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_Icmp_OutDestUnreachs{instance=~\"$node_name\"}[5m]))",
       "legendFormat": "OutDestUnreachs"
      },
      {
       "expr": "avg by (instance) (rate(node_netstat_IcmpMsg_InType3{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_IcmpMsg_InType3{instance=~\"$node_name\"}[5m]))",
       "legendFormat": "InType3 (Destination unreachable)"
      },
      {
       "expr": "avg by (instance) (irate(node_netstat_IcmpMsg_OutType3{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_IcmpMsg_OutType3{instance=~\"$node_name\"}[5m]))",
       "legendFormat": "OutType3 (Destination unreachable)"
      },
      {
       "expr": "avg by (instance) (rate(node_netstat_Icmp_InCsumErrors{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_Icmp_InCsumErrors{instance=~\"$node_name\"}[5m]))",
       "legendFormat": "InCsumErrors"
      },
      {
       "expr": "avg by (instance) (rate(node_netstat_Icmp_InTimeExcds{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_Icmp_InTimeExcds{instance=~\"$node_name\"}[5m]))",
       "legendFormat": "InTimeExcds"
      }
     ]
    },
    {
     "title": "Messages / Redirects",
     "type": "graph",
     "description": "**InMsgs**  Messages which the entity received. Note that this counter includes all those counted by icmpInErrors\t\n\n**InRedirects**  Redirect messages received\t\n\n**OutMsgs**  Messages which this entity attempted to send. Note that this counter includes all those counted by icmpOutErrors\t\n\n**OutRedirects** Redirect messages sent. For a host, this object will always be zero, since hosts do not send redirects",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "ops", "label": "Out (-) / In (+)" }
     ],
     "targets": [
      {
       "expr": "avg by (instance) (rate(node_netstat_Icmp_InMsgs{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_Icmp_InMsgs{instance=~\"$node_name\"}[5m]))",
       "legendFormat": "InMsgs "
      },
      {
       "expr": "avg by (instance) (rate(node_netstat_Icmp_InRedirects{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_Icmp_InRedirects{instance=~\"$node_name\"}[5m]))",
       "legendFormat": "InRedirects"
      },
      {
       "expr": "avg by (instance) (rate(node_netstat_Icmp_OutMsgs{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_Icmp_OutMsgs{instance=~\"$node_name\"}[5m]))",
       "legendFormat": "OutMsgs"
      },
      {
       "expr": "avg by (instance) (rate(node_netstat_Icmp_OutRedirects{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_Icmp_OutRedirects{instance=~\"$node_name\"}[5m]))",
       "legendFormat": "OutRedirects"
      }
     ]
    },
    {
     "title": "Echos",
     "type": "graph",
     "description": "**InEchoReps**  Echo Reply messages received\n\n**InEchos**  Echo (request) messages received\n\n**OutEchoReps** Echo Reply messages sent\n\n**OutEchos**  Echo (request) messages sent",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "ops", "label": "Out (-) / In (+)" }
     ],
     "targets": [
      {
       "expr": "avg by (instance) (rate(node_netstat_Icmp_InEchoReps{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_Icmp_InEchoReps{instance=~\"$node_name\"}[5m]))",
       "legendFormat": "InEchoReps"
      },
      {
       "expr": "avg by (instance) (rate(node_netstat_Icmp_InEchos{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_Icmp_InEchos{instance=~\"$node_name\"}[5m]))",
       "legendFormat": "InEchos "
      },
      {
       "expr": "avg by (instance) (rate(node_netstat_Icmp_OutEchoReps{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_Icmp_OutEchoReps{instance=~\"$node_name\"}[5m]))",
       "legendFormat": "OutEchoReps"
      },
      {
       "expr": "avg by (instance) (rate(node_netstat_Icmp_OutEchos{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_Icmp_OutEchos{instance=~\"$node_name\"}[5m]))",
       "legendFormat": "OutEchos"
      }
     ]
    },
    {
     "title": "Timestamps / Mask Requests",
     "type": "graph",
     "description": "**InAddrMaskReps**  Address Mask Reply messages received\n\n**InAddrMasks** Address Mask Request messages received\n\n**OutAddrMaskReps**  Address Mask Reply messages sent\n\n**OutAddrMasks**  Address Mask Request messages sent\n\n**InTimestampReps**  Timestamp Reply messages received\n\n**InTimestamps**  Timestamp Request messages received\t\n\n**OutTimestampReps** Timestamp Reply messages sent\n\n**OutTimestamps** Timestamp Request messages sent",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "short", "label": "Out (-) / In (+)" }
     ],
     "targets": [
      {
       "expr": "avg by (instance) (rate(node_netstat_Icmp_InAddrMaskReps{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_Icmp_InAddrMaskReps{instance=~\"$node_name\"}[5m]))",
       "legendFormat": "InAddrMaskReps"
      },
      {
       "expr": "avg by (instance) (rate(node_netstat_Icmp_InAddrMasks{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_Icmp_InAddrMasks{instance=~\"$node_name\"}[5m]))",
       "legendFormat": "InAddrMasks"
      },
      {
       "expr": "avg by (instance) (rate(node_netstat_Icmp_OutAddrMaskReps{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_Icmp_OutAddrMaskReps{instance=~\"$node_name\"}[5m]))",
       "legendFormat": "OutAddrMaskReps"
      },
      {
       "expr": "avg by (instance) (rate(node_netstat_Icmp_OutAddrMasks{instance=~\"$node_name\"}[5m]) or\nirate(node_netstat_Icmp_OutAddrMasks{instance=~\"$node_name\"}[5m]))",
       "legendFormat": "OutAddrMasks"
      },
      {
       "expr": "avg by (instance) (rate(node_netstat_Icmp_InTimestampReps{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_Icmp_InTimestampReps{instance=~\"$node_name\"}[5m]))",
       "legendFormat": "InTimestampReps"
      },
      {
       "expr": "avg by (instance) (rate(node_netstat_Icmp_InTimestamps{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_Icmp_InTimestamps{instance=~\"$node_name\"}[5m]))",
       "legendFormat": "InTimestamps"
      },
      {
       "expr": "avg by (instance) (rate(node_netstat_Icmp_OutTimestampReps{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_Icmp_OutTimestampReps{instance=~\"$node_name\"}[5m]))",
       "legendFormat": "OutTimestampReps"
      },
      {
       "expr": "avg by (instance) (rate(node_netstat_Icmp_OutTimestamps{instance=~\"$node_name\"}[$interval]) or\nirate(node_netstat_Icmp_OutTimestamps{instance=~\"$node_name\"}[5m]))",
       "legendFormat": "OutTimestamps"
      }
     ]
    }
   ]
  }
 ]
}