{
 "title": "NFS Full",
 "description": "NFS and NFSd monitor for prometheus-node-exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_nfs_connections_total, job)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_nfs_connections_total{job=~\"$job\"}   , instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(node_boot_time_seconds{instance=~\"$node:(.*)\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "NFS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NFS Connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "irate(node_nfs_connections_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
     "legendFormat": "Number of NFS TCP connections"
    }
   ]
  },
  {
   "title": "NFS Packets",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "pps", "label": "Packets" }
   ],
   "targets": [
    {
     "expr": "irate(node_nfs_packets_total{protocol=\"tcp\",instance=~\"$node:$port\",job=~\"$job\"}[5m])",
     "legendFormat": "TCP - NFS network packets (sent+received)"
    },
    {
     "expr": "irate(node_nfs_packets_total{protocol=\"udp\",instance=~\"$node:$port\",job=~\"$job\"}[5m])",
     "legendFormat": "UDP - NFS network packets (sent+received)"
    }
   ]
  },
  {
   "title": "NFS RPC",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Counter" }
   ],
   "targets": [
    {
     "expr": "irate(node_nfs_rpc_authentication_refreshes_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
     "legendFormat": "Number of RPC authentication refreshes performed"
    },
    {
     "expr": "irate(node_nfs_rpc_retransmissions_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
     "legendFormat": "Number of RPC transmissions performed"
    },
    {
     "expr": "irate(node_nfs_rpcs_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
     "legendFormat": "Total number of RPCs performed"
    }
   ]
  },
  {
   "title": "NFS v2 Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFS v2 NFS Procedures Invoked 1",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_nfs_requests_total{method='Create',proto='2',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='FsStat',proto='2',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='GetAttr',proto='2',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Link',proto='2',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Lookup',proto='2',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='MkDir',proto='2',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Null',proto='2',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Read',proto='2',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='ReadDir',proto='2',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "NFS v2 NFS Procedures Invoked 2",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_nfs_requests_total{method='ReadLink',proto='2',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Remove',proto='2',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Rename',proto='2',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='RmDir',proto='2',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Root',proto='2',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='SetAttr',proto='2',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='SymLink',proto='2',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='WrCache',proto='2',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Write',proto='2',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      }
     ]
    }
   ]
  },
  {
   "title": "NFS v3 Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFS v3 NFS Procedures Invoked 1",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_nfs_requests_total{method='Access',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Commit',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Create',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='FsInfo',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='FsStat',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='GetAttr',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Link',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Lookup',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='MkDir',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='MkNod',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Null',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "NFS v3 NFS Procedures Invoked 2",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_nfs_requests_total{method='PathConf',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Read',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='ReadDir',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='ReadDirPlus',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='ReadLink',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Rename',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='RmDir',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='SetAttr',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='SymLink',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Write',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Remove',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      }
     ]
    }
   ]
  },
  {
   "title": "NFS v4 Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFS v4 NFS Procedures Invoked 1",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_nfs_requests_total{method='Access',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Commit',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Create',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='FsInfo',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='GetAttr',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Link',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Lookup',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Null',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Allocate',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='BindConnToSession',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Clone',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "NFS v4 NFS Procedures Invoked 2",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_nfs_requests_total{method='PathConf',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Read',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='ReadDir',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='ReadLink',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Rename',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Setattr',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='SymLink',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Write',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Close',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='CreateSession',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Read',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "NFS v4 NFS Procedures Invoked 3",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_nfs_requests_total{method='DeAllocate',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='DelegReturn',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='DestroyClientID',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='DestroySession',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='ExchangeID',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='FreeStateID',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='FsLocations',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='FsidPresent',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='GetACL',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='GetDeviceInfo',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "NFS v4 NFS Procedures Invoked 4",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_nfs_requests_total{method='GetDeviceList',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='GetLeaseTime',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='LayoutCommit',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='LayoutGet',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='LayoutReturn',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='LayoutStats',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Lock',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Lockt',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Locku',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Lookup',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "NFS v4 NFS Procedures Invoked 5",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_nfs_requests_total{method='LookupRoot',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Open',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='OpenConfirmt',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='OpenDowngrade',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='OpenNoattr',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='ReclaimComplete',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='ReleaseLockowner',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Renew',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Secinfo',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='SecinfoNoName',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "NFS v4 NFS Procedures Invoked 6",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_nfs_requests_total{method='Seek',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='Sequence',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='ServerCaps',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='SetACL',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='SetClientID',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='SetClientIDConfirm',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='StatFs',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "irate(node_nfs_requests_total{method='TestStateID',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ method }}"
      }
     ]
    }
   ]
  }
 ]
}