{
 "title": "NGINX Ingress controller/Request Handling Performance",
 "tags": [ "nginx" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "ingress",
    "label": "Service Ingress",
    "query": "label_values(nginx_ingress_controller_requests, ingress) "
   }
  ]
 },
 "panels": [
  {
   "title": "Total request handling time",
   "type": "graph",
   "description": "Total time taken for nginx and upstream servers to process a request and send a response",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(  0.5,  sum by (le)(    rate(      nginx_ingress_controller_request_duration_seconds_bucket{        ingress =~ \"$ingress\"      }[1m]    )  ))",
     "legendFormat": ".5"
    },
    {
     "expr": "histogram_quantile(  0.95,  sum by (le)(    rate(    nginx_ingress_controller_request_duration_seconds_bucket{        ingress =~ \"$ingress\"      }[1m]    )  ))",
     "legendFormat": ".95"
    },
    {
     "expr": "histogram_quantile(  0.99,  sum by (le)(    rate(      nginx_ingress_controller_request_duration_seconds_bucket{        ingress =~ \"$ingress\"      }[1m]    )  ))",
     "legendFormat": ".99"
    }
   ]
  },
  {
   "title": "Upstream response time",
   "type": "graph",
   "description": "The time spent on receiving the response from the upstream server",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(  0.5,  sum by (le)(    rate(      nginx_ingress_controller_response_duration_seconds_bucket{        ingress =~ \"$ingress\"      }[1m]    )  ))",
     "legendFormat": ".5"
    },
    {
     "expr": "histogram_quantile(  0.95,  sum by (le)(    rate(    nginx_ingress_controller_response_duration_seconds_bucket{        ingress =~ \"$ingress\"      }[1m]    )  ))",
     "legendFormat": ".95"
    },
    {
     "expr": "histogram_quantile(  0.99,  sum by (le)(    rate(      nginx_ingress_controller_response_duration_seconds_bucket{        ingress =~ \"$ingress\"      }[1m]    )  ))",
     "legendFormat": ".99"
    }
   ]
  },
  {
   "title": "Request volume by Path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "  sum by (path)(    rate(      nginx_ingress_controller_request_duration_seconds_count{        ingress =~ \"$ingress\"      }[1m]    )  )",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Median upstream response time by Path",
   "type": "graph",
   "description": "For each path observed, its median upstream response time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(  .5,  sum by (le, path)(    rate(      nginx_ingress_controller_response_duration_seconds_bucket{        ingress =~ \"$ingress\"      }[1m]    )  ))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Response error rate by Path",
   "type": "graph",
   "description": "Percentage of 4xx and 5xx responses among all responses.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (rate(nginx_ingress_controller_request_duration_seconds_count{  ingress = \"$ingress\",  status =~ \"[4-5].*\"}[1m])) / sum by (path) (rate(nginx_ingress_controller_request_duration_seconds_count{  ingress = \"$ingress\",}[1m]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Upstream time consumed by Path",
   "type": "graph",
   "description": "For each path observed, the sum of upstream request time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (rate(nginx_ingress_controller_response_duration_seconds_sum{ingress = \"$ingress\"}[1m]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Response error volume by Path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "  sum (    rate(      nginx_ingress_controller_request_duration_seconds_count{        ingress =~ \"$ingress\",        status =~\"[4-5].*\",      }[1m]    )  ) by(path, status)",
     "legendFormat": "{{ path }} {{ status }}"
    }
   ]
  },
  {
   "title": "Average response size by Path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (  rate (      nginx_ingress_controller_response_size_sum {        ingress =~ \"$ingress\",      }[1m]  ))  by (path) / sum (  rate(      nginx_ingress_controller_response_size_count {        ingress =~ \"$ingress\",      }[1m]  )) by (path)",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Upstream service latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum (  rate(      nginx_ingress_controller_ingress_upstream_latency_seconds_sum {        ingress =~ \"$ingress\",      }[1m])) / sum (  rate(      nginx_ingress_controller_ingress_upstream_latency_seconds_count {        ingress =~ \"$ingress\",      }[1m]  ))",
     "legendFormat": "average"
    }
   ]
  }
 ]
}