{
 "title": "Node Summary",
 "tags": [
  "OS",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": "label_values(node_uname_info, instance)"
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_name)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, cluster)"
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
   },
   { "name": "schema", "label": "Schema" }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "content": "<h1><i><font color=#5991A7><b><center>Data for </font><font color=#e68a00>$node_name</font> <font color=#5991A7> with</font> </font><font color=#e68a00>$interval</font> <font color=#5991A7>resolution</center></b></font></i></h1>"
  },
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (instance) ((node_time_seconds{instance=~\"$node_name\"} - node_boot_time_seconds{instance=~\"$node_name\"}) or (time() - node_boot_time_seconds{instance=~\"$node_name\"}))"
    }
   ]
  },
  {
   "title": "Virtual CPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(node_cpu_seconds_total{instance=~\"$node_name\",mode=~\"user\"}) or (1-absent(node_cpu_seconds_total{instance=~\"$node_name\",mode=~\"user\"}))) + sum(rdsosmetrics_General_numVCPUs{instance=~\"$node_name\"} or up * 0)"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (instance) (avg_over_time(node_load1{instance=~\"$node_name\"}[$interval]) or avg_over_time(node_load1{instance=~\"$node_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "singlestat",
   "description": "Sum of disk space on all partitions. Note  it can be significantly over-reported in some installations",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (instance) (sum(avg(node_filesystem_size_bytes{instance=~\"$node_name\",fstype=~\"(ext.|xfs|vfat|)\"}) without (mountpoint)) without (device,fstype))"
    }
   ]
  },
  {
   "title": "Min Space Available",
   "type": "singlestat",
   "description": "Lowest percent of the disk space available",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (instance) (min(node_filesystem_free_bytes{instance=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"}/node_filesystem_size_bytes{instance=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"})*100)"
    }
   ]
  },
  {
   "title": "Time before run out of space",
   "type": "singlestat",
   "description": "Estimated time of Disk usage based on trend",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(sum(node_filesystem_free_bytes{fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\",instance=\"$node_name\"})/clamp_min(sum(node_filesystem_free_bytes{fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\",instance=\"$node_name\"} - predict_linear(node_filesystem_free_bytes{fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\",instance=\"$node_name\"}[1h], 1 * 3600)),0))"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (instance) (node_memory_MemTotal_bytes{instance=~\"$node_name\"})"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "singlestat",
   "description": "Percent of Memory Available\nNote: on Modern Linux Kernels amount of Memory Available for application is not the same as Free+Cached+Buffers",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (instance) (((node_memory_MemAvailable_bytes{instance=~\"$node_name\"} or (node_memory_MemFree_bytes{instance=~\"$node_name\"} + node_memory_Buffers_bytes{instance=~\"$node_name\"} + node_memory_Cached_bytes{instance=~\"$node_name\"})) / node_memory_MemTotal_bytes{instance=~\"$node_name\"}) * 100)"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "singlestat",
   "description": "RAM + SWAP",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (instance) ((node_memory_MemTotal_bytes{instance=~\"$node_name\"} + node_memory_SwapTotal_bytes{instance=~\"$node_name\"}))"
    }
   ]
  },
  {
   "title": "DB Service Connections",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum by (service_name) (max_over_time(mysql_global_status_threads_connected{instance=~\"$node_name\"}[$interval]))",
     "legendFormat": "MySQL - {{service_name}}"
    },
    {
     "expr": "sum by (service_name) (max_over_time(mongodb_connections{instance=~\"$node_name\",state=\"current\"}[$interval]))",
     "legendFormat": "MongoDB - {{service_name}}"
    },
    {
     "expr": "sum by (service_name) (max_over_time(pg_stat_database_numbackends{instance=~\"$node_name\"}[$interval]))",
     "legendFormat": "PostgreSQL - {{service_name}}"
    }
   ]
  },
  {
   "title": "Service Types",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count by (service_type) (sum by (service_name,service_type) (max_over_time(mysql_global_status_threads_connected{instance=~\"$node_name\"}[$interval]) or sum by (service_name,service_type) (max_over_time(mongodb_connections{instance=~\"$node_name\",state=\"current\"}[$interval])) or sum by (service_name,service_type) (max_over_time(pg_stat_database_numbackends{instance=~\"$node_name\"}[$interval]))))"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "The CPU time is measured in clock ticks or seconds. It is useful to measure CPU time as a percentage of the CPU's capacity, which is called the CPU usage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (instance,mode) (clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"$node_name\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"$node_name\",mode!=\"idle\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{instance=~\"$node_name\", mode!=\"total\", mode!=\"idle\"}[$interval]) or avg_over_time(node_cpu_average{instance=~\"$node_name\", mode!=\"total\", mode!=\"idle\"}[5m]))),100))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "CPU Saturation and Max Core Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "avg by (instance) ((avg_over_time(node_procs_running{instance=~\"$node_name\"}[$interval])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", instance=~\"$node_name\"})) or (avg_over_time(node_procs_running{instance=~\"$node_name\"}[5m])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", instance=~\"$node_name\"})))",
     "legendFormat": "Normalized CPU Load"
    },
    {
     "calculatedInterval": "2s",
     "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
     "legendFormat": "Max CPU Core Utilization"
    },
    {
     "expr": "avg by (node_name) (aws_rds_cpu_credit_usage_average{instance=~\"$node_name\"})",
     "legendFormat": "CPU Credits Usage"
    }
   ]
  },
  {
   "title": "Interrupts and Context Switches",
   "type": "graph",
   "description": "\nInterrupt is an input signal to the processor indicating an event that needs immediate attention. An interrupt signal alerts the processor and serves as a request for the processor to interrupt the currently executing code, so that the event can be processed in a timely manner.\n\nContext switch is the process of storing the state of a process or thread, so that it can be restored and resume execution at a later point. This allows multiple processes to share a single CPU, and is an essential feature of a multitasking operating system.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance) (rate(node_context_switches_total{instance=~\"$node_name\"}[$interval]) or irate(node_context_switches_total{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Context Switches"
    },
    {
     "expr": "avg by (instance) ((rate(node_context_switches_total{instance=~\"$node_name\"}[$interval]) or irate(node_context_switches_total{instance=~\"$node_name\"}[5m])) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})))",
     "legendFormat": "Context Switches per Virtual CPU"
    },
    {
     "expr": "avg by (instance) (rate(node_intr_total{instance=~\"$node_name\"}[$interval]) or irate(node_intr_total{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Interrupts"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (clamp_min((avg_over_time(node_procs_running{instance=~\"$node_name\"}[$interval]) - 1) or (avg_over_time(node_procs_running{instance=~\"$node_name\"}[5m]) -1),0))",
     "legendFormat": "Runnable Processes"
    },
    {
     "expr": "avg by (instance) (avg_over_time(node_procs_blocked{instance=~\"$node_name\"}[$interval]) or avg_over_time(node_procs_blocked{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Blocked Processes"
    },
    {
     "expr": "avg by (instance) (rate(node_forks_total{instance=~\"$node_name\"}[$interval]) or irate(node_forks_total{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Created Processes (Forks)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "avg by (instance) (max_over_time(node_memory_MemFree_bytes{instance=~\"$node_name\"}[$interval]) or max_over_time(node_memory_MemFree_bytes{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Free"
    },
    {
     "calculatedInterval": "2s",
     "expr": "avg by (instance) (max_over_time(node_memory_Buffers_bytes{instance=~\"$node_name\"}[$interval]) or max_over_time(node_memory_Buffers_bytes{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Buffers"
    },
    {
     "calculatedInterval": "2s",
     "expr": "clamp_min(avg by (instance) (((max_over_time(node_memory_MemTotal_bytes{instance=~\"$node_name\"}[$interval]) or max_over_time(node_memory_MemTotal_bytes{instance=~\"$node_name\"}[5m])) - ((max_over_time(node_memory_MemFree_bytes{instance=~\"$node_name\"}[$interval]) or max_over_time(node_memory_MemFree_bytes{instance=~\"$node_name\"}[5m]))+ \n(max_over_time(node_memory_Buffers_bytes{instance=~\"$node_name\"}[$interval]) or max_over_time(node_memory_Buffers_bytes{instance=~\"$node_name\"}[5m])) + \n(max_over_time(node_memory_Cached_bytes{instance=~\"$node_name\"}[$interval]) or max_over_time(node_memory_Cached_bytes{instance=~\"$node_name\"}[5m]))))),0)",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (instance) (max(max_over_time(node_memory_Cached_bytes{instance=~\"$node_name\",job=~\"rds.*|node.*\"}[$interval]) or max_over_time(node_memory_Cached_bytes{instance=~\"$node_name\",job=~\"rds.*|node.*\"}[5m])) without (job))",
     "legendFormat": "Cache"
    },
    {
     "expr": "avg by (instance) (max_over_time(node_memory_MemTotal_bytes{instance=~\"$node_name\"}[$interval]) or max_over_time(node_memory_MemTotal_bytes{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Virtual Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "avg by (instance) (((max_over_time(node_memory_MemTotal_bytes{instance=~\"$node_name\"}[$interval]) or max_over_time(node_memory_MemTotal_bytes{instance=~\"$node_name\"}[5m])) + \n(max_over_time(node_memory_SwapTotal_bytes{instance=~\"$node_name\"}[$interval]) or max_over_time(node_memory_SwapTotal_bytes{instance=~\"$node_name\"}[5m]))))",
     "legendFormat": "Total"
    },
    {
     "calculatedInterval": "2s",
     "expr": "avg by (instance) ((((max_over_time(node_memory_MemAvailable_bytes{instance=~\"$node_name\"}[$interval]) or max_over_time(node_memory_MemAvailable_bytes{instance=~\"$node_name\"}[5m])) or \n((max_over_time(node_memory_MemFree_bytes{instance=~\"$node_name\"}[$interval]) or max_over_time(node_memory_MemFree_bytes{instance=~\"$node_name\"}[5m]))+ \n(max_over_time(node_memory_Buffers_bytes{instance=~\"$node_name\"}[$interval]) or max_over_time(node_memory_Buffers_bytes{instance=~\"$node_name\"}[5m]))+ \n(max_over_time(node_memory_Cached_bytes{instance=~\"$node_name\"}[$interval]) or max_over_time(node_memory_Cached_bytes{instance=~\"$node_name\"}[5m])))) + \n(max_over_time(node_memory_SwapFree_bytes{instance=~\"$node_name\"}[$interval]) or max_over_time(node_memory_SwapFree_bytes{instance=~\"$node_name\"}[5m]))))",
     "legendFormat": "Available"
    },
    {
     "expr": "avg by (instance) ((max_over_time(node_memory_MemTotal_bytes{instance=~\"$node_name\"}[$interval]) or max_over_time(node_memory_MemTotal_bytes{instance=~\"$node_name\"}[5m])) + \n(max_over_time(node_memory_SwapTotal_bytes{instance=~\"$node_name\"}[$interval]) or max_over_time(node_memory_SwapTotal_bytes{instance=~\"$node_name\"}[5m])) - \n((max_over_time(node_memory_MemAvailable_bytes{instance=~\"$node_name\"}[$interval]) or max_over_time(node_memory_MemAvailable_bytes{instance=~\"$node_name\"}[5m])) or \n((max_over_time(node_memory_MemFree_bytes{instance=~\"$node_name\"}[$interval]) or max_over_time(node_memory_MemFree_bytes{instance=~\"$node_name\"}[5m]))+ \n(max_over_time(node_memory_Buffers_bytes{instance=~\"$node_name\"}[$interval]) or max_over_time(node_memory_Buffers_bytes{instance=~\"$node_name\"}[5m]))+ \n(max_over_time(node_memory_Cached_bytes{instance=~\"$node_name\"}[$interval]) or max_over_time(node_memory_Cached_bytes{instance=~\"$node_name\"}[5m]))) + \n(max_over_time(node_memory_SwapFree_bytes{instance=~\"$node_name\"}[$interval]) or max_over_time(node_memory_SwapFree_bytes{instance=~\"$node_name\"}[5m]))))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Swap Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "avg by (instance) ((max_over_time(node_memory_SwapTotal_bytes{instance=~\"$node_name\"}[$interval]) or max_over_time(node_memory_SwapTotal_bytes{instance=~\"$node_name\"}[5m])) -\n(max_over_time(node_memory_SwapFree_bytes{instance=~\"$node_name\"}[$interval]) or max_over_time(node_memory_SwapFree_bytes{instance=~\"$node_name\"}[5m])))",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "avg by (instance) (max_over_time(node_memory_SwapFree_bytes{instance=~\"$node_name\"}[$interval]) or max_over_time(node_memory_SwapFree_bytes{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Free"
    },
    {
     "expr": "avg by (instance) (max_over_time(node_memory_SwapTotal_bytes{instance=~\"$node_name\"}[$interval]) or max_over_time(node_memory_SwapTotal_bytes{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Swap Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "Bps", "label": "Swap out (-) / Swap in (+)" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "avg by (instance) (rate(node_vmstat_pswpin{instance=~\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{instance=~\"$node_name\"}[5m]) * 4096)",
     "legendFormat": "Swap In (Reads)"
    },
    {
     "calculatedInterval": "2s",
     "expr": "avg by (instance) (rate(node_vmstat_pswpout{instance=~\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{instance=~\"$node_name\"}[5m]) * 4096)",
     "legendFormat": "Swap Out (Writes)"
    },
    {
     "expr": "avg by (instance) ((rate(node_vmstat_pswpin{instance=~\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{instance=~\"$node_name\"}[5m]) * 4096) + (rate(node_vmstat_pswpout{instance=~\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{instance=~\"$node_name\"}[5m]) * 4096))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "I/O Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "Bps", "label": "Page Out (-) / Page In (+)" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "avg by (instance) (rate(node_vmstat_pgpgin{instance=~\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=~\"$node_name\"}[5m]) * 1024 or\n(max_over_time(rdsosmetrics_diskIO_readKbPS{instance=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_readKbPS{instance=~\"$node_name\"}[5m])) * 1024)",
     "legendFormat": "Disk Reads (Page In)"
    },
    {
     "calculatedInterval": "2s",
     "expr": "avg by (instance) ((rate(node_vmstat_pgpgout{instance=~\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=~\"$node_name\"}[5m]) * 1024) or\n(max_over_time(rdsosmetrics_diskIO_writeKbPS{instance=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_writeKbPS{instance=~\"$node_name\"}[5m])) * 1024)",
     "legendFormat": "Disk Writes (Page Out)"
    },
    {
     "expr": "avg by (instance) ((rate(node_vmstat_pgpgin{instance=~\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=~\"$node_name\"}[5m]) * 1024 ) + (rate(node_vmstat_pgpgout{instance=~\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=~\"$node_name\"}[5m]) * 1024) or\n((max_over_time(rdsosmetrics_diskIO_writeKbPS{instance=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_writeKbPS{instance=~\"$node_name\"}[5m])) +\n(max_over_time(rdsosmetrics_diskIO_readKbPS{instance=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_readKbPS{instance=~\"$node_name\"}[5m])))* 1024)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Global File Descriptors Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "avg by (instance) (max_over_time(node_filefd_maximum{instance=~\"$node_name\"}[$interval]) or max_over_time(node_filefd_maximum{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Limit"
    },
    {
     "calculatedInterval": "2s",
     "expr": "avg by (instance) (max_over_time(node_filefd_allocated{instance=~\"$node_name\"}[$interval]) or max_over_time(node_filefd_allocated{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Disk IO Latency",
   "type": "graph",
   "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal storage problems.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) ((sum(rate(node_disk_read_time_seconds_total{instance=~\"$node_name\"}[$interval])) / sum(rate(node_disk_reads_completed_total{instance=~\"$node_name\"}[$interval]))) or (sum(irate(node_disk_read_time_seconds_total{instance=~\"$node_name\"}[5m])) / sum(irate(node_disk_reads_completed_total{instance=~\"$node_name\"}[5m])))\nor avg_over_time(aws_rds_read_latency_average{instance=~\"$node_name\"}[$interval])/1000 or avg_over_time(aws_rds_read_latency_average{instance=~\"$node_name\"}[5m])/1000 or\navg_over_time(rdsosmetrics_diskIO_readLatency{instance=~\"$node_name\"}[$interval])/1000 or avg_over_time(rdsosmetrics_diskIO_readLatency{instance=~\"$node_name\"}[5m])/1000)",
     "legendFormat": "Read Latency"
    },
    {
     "expr": "avg by (instance) ((sum(rate(node_disk_write_time_seconds_total{instance=~\"$node_name\"}[$interval])) / sum(rate(node_disk_writes_completed_total{instance=~\"$node_name\"}[$interval]))) or (sum(irate(node_disk_write_time_seconds_total{instance=~\"$node_name\"}[5m])) / sum(irate(node_disk_writes_completed_total{instance=~\"$node_name\"}[5m])))\nor (avg_over_time(aws_rds_write_latency_average{instance=~\"$node_name\"}[$interval])/1000 or avg_over_time(aws_rds_write_latency_average{instance=~\"$node_name\"}[5m])/1000) or\n(avg_over_time(rdsosmetrics_diskIO_writeLatency{instance=~\"$node_name\"}[$interval]) or avg_over_time(rdsosmetrics_diskIO_writeLatency{instance=~\"$node_name\"}[5m]))/1000)",
     "legendFormat": "Write Latency"
    },
    {
     "expr": "avg by (instance) ((sum(rate(node_disk_read_time_seconds_total{instance=~\"$node_name\"}[1h])) / sum(rate(node_disk_reads_completed_total{instance=~\"$node_name\"}[1h])))\nor avg_over_time(aws_rds_read_latency_average{instance=~\"$node_name\"}[1h])/1000 or avg_over_time(aws_rds_read_latency_average{instance=~\"$node_name\"}[1h])/1000 or\navg_over_time(rdsosmetrics_diskIO_readLatency{instance=~\"$node_name\"}[1h])/1000 or avg_over_time(rdsosmetrics_diskIO_readLatency{instance=~\"$node_name\"}[1h])/1000)",
     "legendFormat": "Avg Read Latency (1h)"
    },
    {
     "expr": "avg by (instance) ((sum(rate(node_disk_write_time_seconds_total{instance=~\"$node_name\"}[1h])) / sum(rate(node_disk_writes_completed_total{instance=~\"$node_name\"}[1h]))) \nor (avg_over_time(aws_rds_write_latency_average{instance=~\"$node_name\"}[$interval])/1000 or avg_over_time(aws_rds_write_latency_average{instance=~\"$node_name\"}[1h])/1000) or\n(avg_over_time(rdsosmetrics_diskIO_writeLatency{instance=~\"$node_name\"}[$interval])/1000 or avg_over_time(rdsosmetrics_diskIO_writeLatency{instance=~\"$node_name\"}[1h])/1000))",
     "legendFormat": "Avg Write Latency (1h)"
    }
   ]
  },
  {
   "title": "Disk IO Load",
   "type": "graph",
   "description": "Shows how much disk was loaded for reads or writes as average number of outstanding requests at different period of time.  High disk load is a good measure of actual storage utilization. Different storage types handle load differently - some will show latency increases on low loads others can handle higher load with no problems.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "Write Load (-) / Read Load (+)" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance) (sum(rate(node_disk_read_time_seconds_total{instance=~\"$node_name\"}[$interval])) or sum(irate(node_disk_read_time_seconds_total{instance=~\"$node_name\"}[5m])) or\n(sum(rdsosmetrics_diskIO_readIOsPS{instance=~\"$node_name\"})))",
     "legendFormat": "Read Load"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance) (sum(rate(node_disk_write_time_seconds_total{instance=~\"$node_name\"}[$interval])) or sum(irate(node_disk_write_time_seconds_total{instance=~\"$node_name\"}[5m])) or (sum(rdsosmetrics_diskIO_writeIOsPS{instance=~\"$node_name\"})))",
     "legendFormat": "Write Load"
    },
    {
     "expr": "avg by (instance) ((sum(rate(node_disk_read_time_seconds_total{instance=~\"$node_name\"}[$interval])) or sum(irate(node_disk_read_time_seconds_total{instance=~\"$node_name\"}[5m]))) + (sum(rate(node_disk_write_time_seconds_total{instance=~\"$node_name\"}[$interval])) or sum(irate(node_disk_write_time_seconds_total{instance=~\"$node_name\"}[5m]))) or\n(sum(rdsosmetrics_diskIO_writeIOsPS{instance=~\"$node_name\"})) +  (sum(rdsosmetrics_diskIO_readIOsPS{instance=~\"$node_name\"})))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "Bps", "label": "Outbound (-) / Inbound (+)" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"$node_name\", device!=\"lo\"}[$interval])) or sum(irate(node_network_receive_bytes_total{instance=~\"$node_name\", device!=\"lo\"}[5m])) or sum(max_over_time(rdsosmetrics_network_rx{instance=~\"$node_name\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_rx{instance=~\"$node_name\"}[5m])) ",
     "legendFormat": "Inbound"
    },
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=~\"$node_name\", device!=\"lo\"}[$interval])) or sum(irate(node_network_transmit_bytes_total{instance=~\"$node_name\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{instance=~\"$node_name\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_tx{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Network Utilization Hourly",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(increase(node_network_receive_bytes_total{instance=~\"$node_name\", device!=\"lo\"}[1h])) or sum(increase(rdsosmetrics_network_rx{instance=~\"$node_name\", device!=\"lo\"}[1h]))",
     "legendFormat": "Received"
    },
    {
     "calculatedInterval": "2s",
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\"$node_name\", device!=\"lo\"}[1h])) or sum(increase(rdsosmetrics_network_tx{instance=~\"$node_name\", device!=\"lo\"}[1h]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "(sum(increase(node_network_receive_bytes_total{instance=~\"$node_name\", device!=\"lo\"}[1h]))+sum(increase(node_network_transmit_bytes_total{instance=~\"$node_name\", device!=\"lo\"}[1h])))  or (sum(increase(rdsosmetrics_network_rx{instance=~\"$node_name\", device!=\"lo\"}[1h]))+sum(increase(rdsosmetrics_network_tx{instance=~\"$node_name\", device!=\"lo\"}[1h])))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Local Network Errors",
   "type": "graph",
   "description": "Total Number of Local Network Interface Transmit Errors, Receive Errors and Drops.  Should be  Zero",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_network_receive_errs_total{instance=~\"$node_name\", device!=\"lo\"}[$interval])) or \nsum(irate(node_network_receive_errs_total{instance=~\"$node_name\", device!=\"lo\"}[5m]))",
     "legendFormat": "Receive Errors"
    },
    {
     "expr": "sum(rate(node_network_transmit_errs_total{instance=~\"$node_name\", device!=\"lo\"}[$interval])) or\nsum(irate(node_network_transmit_errs_total{instance=~\"$node_name\", device!=\"lo\"}[5m]))",
     "legendFormat": "Transmit Errors"
    },
    {
     "expr": "sum(rate(node_network_receive_drop_total{instance=~\"$node_name\", device!=\"lo\"}[$interval])) or\nsum(irate(node_network_receive_drop_total{instance=~\"$node_name\", device!=\"lo\"}[5m]))",
     "legendFormat": "Receive Drop"
    },
    {
     "expr": "sum(rate(node_network_transmit_drop_total{instance=~\"$node_name\", device!=\"lo\"}[$interval])) or \nsum(irate(node_network_transmit_drop_total{instance=~\"$node_name\", device!=\"lo\"}[5m]))",
     "legendFormat": "Transmit Drop"
    }
   ]
  },
  {
   "title": "TCP Retransmission",
   "type": "graph",
   "description": "Retransmission, essentially identical with Automatic repeat request (ARQ), is the resending of packets which have been either damaged or lost. Retransmission is one of the basic mechanisms used by protocols operating over a packet switched computer network to provide reliable communication (such as that provided by a reliable byte stream, for example TCP).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "avg by (instance) (rate(node_netstat_Tcp_RetransSegs{instance=~\"$node_name\"}[$interval]) or irate(node_netstat_Tcp_RetransSegs{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Segments Retransmitted"
    },
    {
     "expr": "avg by (instance) (rate(node_netstat_Tcp_RetransSegs{instance=~\"$node_name\"}[$interval])/rate(node_netstat_Tcp_OutSegs{instance=~\"$node_name\"}[$interval]) or irate(node_netstat_Tcp_RetransSegs{instance=~\"$node_name\"}[5m])/irate(node_netstat_Tcp_OutSegsSegs{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Retransmit Ratio"
    }
   ]
  }
 ]
}