{
 "title": "Prometheus AlertManager",
 "description": "The dashborad using Prometheus AlertManager datasource 0.0.6 version.",
 "tags": [ "0.0.1" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "All alerts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "labelSelector": "*", "target": "Query", "type": "single" }
   ]
  },
  {
   "title": " NodeDiskUseage <20%",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertname=\"NodeDiskUseage\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Down Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"NodeDown\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "High Memory Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"NodeMemoryUsageTooHigh95%\"\n",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "High CPU Node",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"NodeCPUUsage95%\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "告警发送统计",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"})",
     "legendFormat": "发送告警"
    },
    {
     "expr": "count(ALERTS{alertstate=\"pending\"})",
     "legendFormat": "挂起告警"
    }
   ]
  },
  {
   "title": "All Alerts Info",
   "type": "table-old",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "labelSelector": "alertname,severity,description,message,namespace,pod,",
     "target": "Query",
     "type": "table"
    }
   ]
  }
 ]
}