{
 "title": "Prometheus2.0",
 "description": "Dashboard for monitoring",
 "tags": [ "Prometheus" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "aggregation_interval",
    "label": "aggregation intarval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(Prometheus_build_info, instance)"
   },
   { "name": "scrape_interval", "label": "Scrape interval seconds", "query": "${VAR_SCRAPE_INTERVAL}" },
   { "name": "datasource", "label": "Prometheus datasource", "query": "Prometheus" },
   { "name": "influx_datasource", "label": "InfluxDB datasource", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "Header instance info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total count of time series",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "Prometheus_tsdb_head_series{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "format": "accMS2",
   "valueName": "current",
   "targets": [
    { "expr": "Prometheus_build_info" }
   ]
  },
  {
   "title": "Actual head block length",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "Prometheus_tsdb_head_max_time - Prometheus_tsdb_head_min_time{instance=\"$instance\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 1 },
   "content": "<img src=\"https://cdn.worldvectorlogo.com/logos/Prometheus.svg\"/ height=\"140px\">"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "2" }
   ]
  },
  { "title": "Main info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Query elapsed time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(Prometheus_engine_query_duration_seconds{instance=\"$instance\"}) by (instance, slice)",
     "legendFormat": "max duration for {{slice}}"
    }
   ]
  },
  {
   "title": "Head series created/deleted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(Prometheus_tsdb_head_series_created_total{instance=\"$instance\"}[$aggregation_interval])) by (instance)",
     "legendFormat": "created on {{ instance }}"
    },
    {
     "expr": "sum(increase(Prometheus_tsdb_head_series_removed_total{instance=\"$instance\"}[$aggregation_interval])) by (instance) * -1",
     "legendFormat": "removed on {{ instance }}"
    }
   ]
  },
  {
   "title": "Prometheus errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(Prometheus_target_scrapes_exceeded_sample_limit_total{instance=\"$instance\"}[$aggregation_interval])) by (instance) > 0",
     "legendFormat": "exceeded_sample_limit on {{ instance }}"
    },
    {
     "expr": "sum(increase(Prometheus_target_scrapes_sample_duplicate_timestamp_total{instance=\"$instance\"}[$aggregation_interval])) by (instance) > 0",
     "legendFormat": "duplicate_timestamp on {{ instance }}"
    },
    {
     "expr": "sum(increase(Prometheus_target_scrapes_sample_out_of_bounds_total{instance=\"$instance\"}[$aggregation_interval])) by (instance) > 0",
     "legendFormat": "out_of_bounds on {{ instance }}"
    },
    {
     "expr": "sum(increase(Prometheus_target_scrapes_sample_out_of_order_total{instance=\"$instance\"}[$aggregation_interval])) by (instance) > 0",
     "legendFormat": "out_of_order on {{ instance }}"
    },
    {
     "expr": "sum(increase(Prometheus_rule_evaluation_failures_total{instance=\"$instance\"}[$aggregation_interval])) by (instance) > 0",
     "legendFormat": "rule_evaluation_failure on {{ instance }}"
    },
    {
     "expr": "sum(increase(Prometheus_tsdb_compactions_failed_total{instance=\"$instance\"}[$aggregation_interval])) by (instance) > 0",
     "legendFormat": "tsdb_compactions_failed on {{ instance }}"
    },
    {
     "expr": "sum(increase(Prometheus_tsdb_reloads_failures_total{instance=\"$instance\"}[$aggregation_interval])) by (instance) > 0",
     "legendFormat": "tsdb_reloads_failures on {{ instance }}"
    },
    {
     "expr": "sum(increase(Prometheus_tsdb_head_series_not_found{instance=\"$instance\"}[$aggregation_interval])) by (instance) > 0",
     "legendFormat": "head_series_not_found on {{ instance }}"
    },
    {
     "expr": "sum(increase(Prometheus_evaluator_iterations_missed_total{instance=\"$instance\"}[$aggregation_interval])) by (instance) > 0",
     "legendFormat": "evaluator_iterations_missed on {{ instance }}"
    },
    {
     "expr": "sum(increase(Prometheus_evaluator_iterations_skipped_total{instance=\"$instance\"}[$aggregation_interval])) by (instance) > 0",
     "legendFormat": "evaluator_iterations_skipped on {{ instance }}"
    }
   ]
  },
  { "title": "Scrape & rule duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Scrape delay (counts with 1m scrape interval)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "Prometheus_target_interval_length_seconds{instance=\"$instance\",quantile=\"0.99\"} - $scrape_interval",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rule evaulation duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(Prometheus_evaluator_duration_seconds{instance=\"$instance\"}) by (instance, quantile)",
     "legendFormat": "Queue length"
    }
   ]
  },
  { "title": "Requests & queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Request count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{instance=\"$instance\"}[$aggregation_interval])) by (instance, handler) > 0",
     "legendFormat": "{{ handler }} on {{ instance }}"
    }
   ]
  },
  {
   "title": "Request duration per handler",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "max(sum(http_request_duration_microseconds{instance=\"$instance\"}) by (instance, handler, quantile)) by (instance, handler) > 0",
     "legendFormat": "{{ handler }} on {{ instance }}"
    }
   ]
  },
  {
   "title": "Request size by handler",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_size_bytes{instance=\"$instance\", quantile=\"0.99\"}[$aggregation_interval])) by (instance, handler) > 0",
     "legendFormat": "{{ handler }} in {{ instance }}"
    }
   ]
  },
  {
   "title": "Cont of concurent queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(Prometheus_engine_queries{instance=\"$instance\"}) by (instance, handler)",
     "legendFormat": "Current count "
    },
    {
     "expr": "sum(Prometheus_engine_queries_concurrent_max{instance=\"$instance\"}) by (instance, handler)",
     "legendFormat": "Max count"
    }
   ]
  },
  { "title": "Alerting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Alert queue size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(Prometheus_notifications_queue_capacity{instance=\"$instance\"})by (instance)",
     "legendFormat": "Alert queue capacity "
    },
    {
     "expr": "sum(Prometheus_notifications_queue_length{instance=\"$instance\"})by (instance)",
     "legendFormat": "Alert queue size on "
    }
   ]
  },
  {
   "title": "Count of discovered alertmanagers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(Prometheus_notifications_alertmanagers_discovered{instance=\"$instance\"}) by (instance)",
     "legendFormat": "Checkpoint chunks written/s"
    }
   ]
  },
  {
   "title": "Alerting errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(Prometheus_notifications_dropped_total{instance=\"$instance\"}[$aggregation_interval])) by (instance) > 0",
     "legendFormat": "notifications_dropped on {{ instance }}"
    },
    {
     "expr": "sum(increase(Prometheus_rule_evaluation_failures_total{rule_type=\"alerting\",instance=\"$instance\"}[$aggregation_interval])) by (rule_type,instance) > 0",
     "legendFormat": "rule_evaluation_failures on {{ instance }}"
    }
   ]
  },
  { "title": "Service discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Consul SD sync count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(Prometheus_target_sync_length_seconds_count{scrape_job=\"consul\", instance=\"$instance\"}[$aggregation_interval])",
     "legendFormat": "Consul target sync count"
    }
   ]
  },
  {
   "title": "Marathon SD sync count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(Prometheus_target_sync_length_seconds_count{scrape_job=\"marathon\", instance=\"$instance\"}[$aggregation_interval])",
     "legendFormat": "Marathon target sync count"
    }
   ]
  },
  {
   "title": "Kubernetes SD sync count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(Prometheus_target_sync_length_seconds_count{scrape_job=\"kubernetes\"}[$aggregation_interval])",
     "legendFormat": "Count of target synces"
    }
   ]
  },
  {
   "title": "Service discovery errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(Prometheus_target_scrapes_exceeded_sample_limit_total{instance=\"$instance\"}[$aggregation_interval])) by (instance) > 0",
     "legendFormat": "exceeded_sample_limit on {{ instance }}"
    },
    {
     "expr": "sum(increase(Prometheus_sd_file_read_errors_total{instance=\"$instance\"}[$aggregation_interval])) by (instance) > 0",
     "legendFormat": "sd_file_read_error on {{ instance }}"
    },
    {
     "expr": "sum(increase(Prometheus_sd_consul_rpc_failures_total{instance=\"$instance\"}[$aggregation_interval])) by (instance) > 0",
     "legendFormat": "sd_consul_rpc_failure on {{ instance }}"
    },
    {
     "expr": "sum(increase(Prometheus_sd_marathon_refresh_failures_total{instance=\"$instance\"}[$aggregation_interval])) by (instance) > 0",
     "legendFormat": "sd_marathon_refresh_failure on {{ instance }}"
    },
    {
     "expr": "sum(increase(Prometheus_sd_openstack_refresh_failures_total{instance=\"$instance\"}[$aggregation_interval])) by (instance) > 0",
     "legendFormat": "sd_openstack_refresh_failure on {{ instance }}"
    }
   ]
  },
  { "title": "TSDB stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Reloaded block from disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(Prometheus_tsdb_reloads_total{instance=\"$instance\"}[30m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Loaded data blocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(Prometheus_tsdb_blocks_loaded{instance=\"$instance\"}) by (instance)",
     "legendFormat": "Loaded data blocks"
    }
   ]
  },
  {
   "title": "Time series total count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Prometheus_tsdb_head_series{instance=\"$instance\"}",
     "legendFormat": "Time series count"
    }
   ]
  },
  {
   "title": "Samples Appended per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(Prometheus_tsdb_head_samples_appended_total{instance=\"$instance\"}[$aggregation_interval])) by (instance)",
     "legendFormat": "samples/s {{instance}}"
    }
   ]
  },
  { "title": "Head block stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Head chunks count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(Prometheus_tsdb_head_chunks{instance=\"$instance\"}) by (instance)",
     "legendFormat": "Head chunk count"
    }
   ]
  },
  {
   "title": "Length of head block",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 55 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(Prometheus_tsdb_head_max_time{instance=\"$instance\"}) by (instance) - min(Prometheus_tsdb_head_min_time{instance=\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Head Chunks Created/Deleted per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(Prometheus_tsdb_head_chunks_created_total{instance=\"$instance\"}[$aggregation_interval])) by (instance)",
     "legendFormat": "created on {{ instance }}"
    },
    {
     "expr": "sum(rate(Prometheus_tsdb_head_chunks_removed_total{instance=\"$instance\"}[$aggregation_interval])) by (instance) * -1",
     "legendFormat": "deleted on {{ instance }}"
    }
   ]
  },
  { "title": "Data maintenance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Compaction duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(Prometheus_tsdb_compaction_duration_sum{instance=\"$instance\"}[30m]) / increase(Prometheus_tsdb_compaction_duration_count{instance=\"$instance\"}[30m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Go Garbage collection duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(Prometheus_tsdb_head_gc_duration_seconds{instance=\"$instance\"}) by (instance, quantile)",
     "legendFormat": "{{ quantile }} on {{ instance }}"
    }
   ]
  },
  {
   "title": "WAL truncate duration seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(Prometheus_tsdb_wal_truncate_duration_seconds{instance=\"$instance\"}) by (instance, quantile)",
     "legendFormat": "{{ quantile }} on {{ instance }}"
    }
   ]
  },
  {
   "title": "WAL fsync duration seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(tsdb_wal_fsync_duration_seconds{instance=\"$instance\"}) by (instance, quantile)",
     "legendFormat": "{{ quantile }} {{ instance }}"
    }
   ]
  },
  { "title": "RAM&CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{instance=\"$instance\"}) by (instance)",
     "legendFormat": "Total resident memory - {{instance}}"
    },
    {
     "expr": "sum(go_memstats_alloc_bytes{instance=\"$instance\"}) by (instance)",
     "legendFormat": "Total llocated bytes - {{instance}}"
    }
   ]
  },
  {
   "title": "Allocations per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 71 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=\"$instance\"}[$aggregation_interval])",
     "legendFormat": "Allocated Bytes/s"
    }
   ]
  },
  {
   "title": "CPU per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 71 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=\"$instance\"}[$aggregation_interval])) by (instance)",
     "legendFormat": "CPU/s"
    }
   ]
  },
  { "title": "Heapster description", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Heapster rows",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 79 },
   "content": "Two rows bellow can serve as example if you are running **Prometheus** in **Kubernetes** and uses **Heapster** with **InfluxDB**.\n\nThe schema and queries are very hard to generalize so you will have to tweak them but I leave them here for inspiration."
  },
  {
   "title": "Heapster RAM&CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage/s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\")/1000 as \"usage_rate.mean\"  FROM \"cpu/usage_rate\" WHERE \"type\" = 'pod_container' AND \"container\" =~ /Prometheus/  AND $timeFilter GROUP BY container, time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\")/1000 as \"usage_rate.mean\"  FROM \"cpu/usage_rate\" WHERE \"type\" = 'pod_container' AND \"container\" =~ /Prometheus/  AND $timeFilter GROUP BY container, time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\")/1000 as \"CPU LIMIT\"  FROM \"cpu/limit\" WHERE \"type\" = 'pod_container' AND \"container\" =~ /Prometheus/  AND $timeFilter GROUP BY container, time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 83 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") as \"usage_rate.mean\"  FROM \"memory/usage\" WHERE \"type\" = 'pod_container' AND \"container\" =~ /Prometheus/  AND $timeFilter GROUP BY container, time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") as \"usage_rate.mean\"  FROM \"memory/usage\" WHERE \"type\" = 'pod_container' AND \"container\" =~ /Prometheus/  AND $timeFilter GROUP BY container, time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") as \"CPU LIMIT\"  FROM \"memory/limit\" WHERE \"type\" = 'pod_container' AND \"container\" =~ /Prometheus/  AND $timeFilter GROUP BY container, time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Heapster host stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network rx[IN] / tx[OUT] in bytes/s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") as \"rx_rate.mean \"  FROM \"network/rx_rate\"  WHERE  \"labels\" =~ /app:Prometheus/  AND $timeFilter GROUP BY labels,  time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") as \"rx_rate.mean\"  FROM \"network/rx_rate\"  WHERE  \"labels\" =~ /app:Prometheus/ AND $timeFilter GROUP BY  labels,  time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\")*-1 as \"tx_rate.mean \"  FROM \"network/tx_rate\"  WHERE  \"labels\" =~ /app:Prometheus/ AND $timeFilter GROUP BY labels,  time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\")*-1 as \"tx_rate.mean\"  FROM \"network/tx_rate\"  WHERE  \"labels\" =~ /app:Prometheus/ AND $timeFilter GROUP BY  labels, time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") as \"rx_errors_rate.mean\"  FROM \"network/rx_errors_rate\"  WHERE  \"labels\" =~ /app:Prometheus/ AND $timeFilter AND \"value\">0 GROUP BY  labels,  time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") as \"rx_errors_rate.mean\"  FROM \"network/rx_errors_rate\"  WHERE  \"labels\" =~ /app:Prometheus/ AND $timeFilter AND \"value\">0 GROUP BY  labels,  time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") as \"tx_errors_rate.mean\"  FROM \"network/rx_errors_rate\"  WHERE  \"labels\" =~ /app:Prometheus/ AND $timeFilter AND \"value\">0 GROUP BY  labels,  time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") as \"tx_errors_rate.mean\"  FROM \"network/rx_errors_rate\"  WHERE  \"labels\" =~ /app:Prometheus/ AND $timeFilter AND \"value\">0 GROUP BY  labels,  time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 10, "y": 84 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") as \"DISK_USAGE.mean \"  FROM \"filesystem/usage\" WHERE  \"labels\" =~ /data-Prometheus:true/ AND $timeFilter GROUP BY  time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") as \"DISK_USAGE.mean \"  FROM \"filesystem/usage\" WHERE  \"labels\" =~ /data-Prometheus:true/ AND $timeFilter GROUP BY  time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") as \"DISK_LIMIT.mean \"  FROM \"filesystem/limit\" WHERE  \"labels\" =~ /data-Prometheus:true/ AND $timeFilter GROUP BY  time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") as \"DISK_LIMIT.mean\"  FROM \"filesystem/limit\" WHERE  \"labels\" =~ /data-Prometheus:true/ AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Number of free INODES",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") as \"FREE_INODES.mean \"  FROM \"filesystem/inodes_free\" WHERE  \"labels\" =~ /data-Prometheus:true/ AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") as \"FREE_INODES.mean\"  FROM \"filesystem/inodes_free\" WHERE  \"labels\" =~ /data-Prometheus:true/ AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") as \"USED_INODES.mean \"  FROM \"filesystem/inodes\" WHERE  \"labels\" =~ /data-Prometheus:true/ AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") as \"USED_INODES.mean\"  FROM \"filesystem/inodes\" WHERE  \"labels\" =~ /data-Prometheus:true/ AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Contrac errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Net errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(net_conntrack_dialer_conn_failed_total{instance=\"$instance\"}[$aggregation_interval])) by (instance) > 0",
     "legendFormat": "conntrack_dialer_conn_failed on {{ instance }}"
    }
   ]
  }
 ]
}