apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: mysql-rules
  namespace: monitoring
spec:
  groups:
  - name: mysql.rules
    rules:
    - record: mysql_slave_lag_seconds
      expr: mysql_slave_status_seconds_behind_master - mysql_slave_status_sql_delay
    - record: mysql_heartbeat_lag_seconds
      expr: mysql_heartbeat_now_timestamp_seconds - mysql_heartbeat_stored_timestamp_seconds
    - record: job:mysql_transactions:rate5m
      expr: sum(rate(mysql_global_status_commands_total{command=~"(commit|rollback)"}[5m]))
        WITHOUT (command)
    - alert: MySQLGaleraNotReady
      expr: mysql_global_status_wsrep_ready != 1
      for: 5m
      labels:
        severity: warning
      annotations:
        description: '{{$labels.job}} on {{$labels.instance}} is not ready.'
        summary: Galera cluster node not ready
    - alert: MySQLGaleraOutOfSync
      expr: (mysql_global_status_wsrep_local_state != 4 and mysql_global_variables_wsrep_desync
        == 0)
      for: 5m
      labels:
        severity: warning
      annotations:
        description: '{{$labels.job}} on {{$labels.instance}} is not in sync ({{$value}}
          != 4).'
        summary: Galera cluster node out of sync
    - alert: MySQLGaleraDonorFallingBehind
      expr: (mysql_global_status_wsrep_local_state == 2 and mysql_global_status_wsrep_local_recv_queue
        > 100)
      for: 5m
      labels:
        severity: warning
      annotations:
        description: '{{$labels.job}} on {{$labels.instance}} is a donor (hotbackup)
          and is falling behind (queue size {{$value}}).'
        summary: xtradb cluster donor node falling behind
    - alert: MySQLReplicationNotRunning
      expr: mysql_slave_status_slave_io_running == 0 or mysql_slave_status_slave_sql_running
        == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        description: Slave replication (IO or SQL) has been down for more than 2 minutes.
        summary: Slave replication is not running
    - alert: MySQLReplicationLag
      expr: (mysql_slave_lag_seconds > 30) and ON(instance) (predict_linear(mysql_slave_lag_seconds[5m],
        60 * 2) > 0)
      for: 1m
      labels:
        severity: critical
      annotations:
        description: The mysql slave replication has fallen behind and is not recovering
        summary: MySQL slave replication is lagging
    - alert: MySQLReplicationLag
      expr: (mysql_heartbeat_lag_seconds > 30) and ON(instance) (predict_linear(mysql_heartbeat_lag_seconds[5m],
        60 * 2) > 0)
      for: 1m
      labels:
        severity: critical
      annotations:
        description: The mysql slave replication has fallen behind and is not recovering
        summary: MySQL slave replication is lagging
    - alert: MySQLInnoDBLogWaits
      expr: rate(mysql_global_status_innodb_log_waits[15m]) > 10
      labels:
        severity: warning
      annotations:
        description: The innodb logs are waiting for disk at a rate of {{$value}} /
          second
        summary: MySQL innodb log writes stalling                
    - alert: MySQL Status 
        expr: up == 0
        for: 5s 
        labels:
          severity: warning
        annotations:
          summary: "{{$labels.instance}}: MySQL has stop !!!"
          description: "检测MySQL数据库运行状态"

    - alert: MySQL Slave IO Thread Status
      expr: mysql_slave_status_slave_io_running == 0
      for: 5s 
      labels:
        severity: warning
      annotations: 
        summary: "{{$labels.instance}}: MySQL Slave IO Thread has stop !!!"
        description: "检测MySQL主从IO线程运行状态"

    - alert: MySQL Slave SQL Thread Status 
      expr: mysql_slave_status_slave_sql_running == 0
      for: 5s 
      labels:
        severity: warning
      annotations: 
        summary: "{{$labels.instance}}: MySQL Slave SQL Thread has stop !!!"
        description: "检测MySQL主从SQL线程运行状态"

    - alert: MySQL Slave Delay Status 
      expr: mysql_slave_status_sql_delay == 30
      for: 5s 
      labels:
        severity: warning
      annotations: 
        summary: "{{$labels.instance}}: MySQL Slave Delay has more than 30s !!!"
        description: "检测MySQL主从延时状态"

    - alert: Mysql_Too_Many_Connections
      expr: rate(mysql_global_status_threads_connected[5m]) > 200
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "{{$labels.instance}}: 连接数过多"
        description: "{{$labels.instance}}: 连接数过多，请处理 ,(current value is: {{ $value }})"  

    - alert: Mysql_Too_Many_slow_queries
      expr: rate(mysql_global_status_slow_queries[5m]) > 3
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "{{$labels.instance}}: 慢查询有点多，请检查处理"
        description: "{{$labels.instance}}: Mysql slow_queries is more than 3 per second ,(current value is: {{ $value }})"