{
 "title": "ECS Aliyun",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(aliyun_meta_ecs_info,environment)"
   },
   {
    "name": "Vpcip",
    "query": "label_values(aliyun_meta_ecs_info{environment=~\"$env\"}, VpcAttributes)"
   },
   {
    "name": "InstanceName",
    "query": "label_values(aliyun_meta_ecs_info   {VpcAttributes=\"$Vpcip\"},  InstanceName)"
   },
   {
    "name": "hostname",
    "query": "label_values(aliyun_meta_ecs_info   {InstanceName=\"$InstanceName\", VpcAttributes=\"$Vpcip\"},  HostName)"
   },
   {
    "name": "instanceId",
    "query": "label_values(aliyun_meta_ecs_info{HostName=\"$hostname\",  VpcAttributes=\"$Vpcip\" }, InstanceId)"
   }
  ]
 },
 "panels": [
  {
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "aliyun_meta_ecs_info{InstanceId=\"$instanceId\"}"
    }
   ]
  },
  {
   "title": "空闲CPU百分比",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "aliyun_acs_ecs_dashboard_cpu_idle{instanceId=\"$instanceId\"}"
    }
   ]
  },
  {
   "title": "CPU百分比",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "aliyun_acs_ecs_dashboard_CPUUtilization{instanceId=\"$instanceId\"}",
     "legendFormat": "CPU百分比"
    }
   ]
  },
  {
   "title": "内核空间占用CPU百分比",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aliyun_acs_ecs_dashboard_cpu_system{instanceId=\"$instanceId\"}",
     "legendFormat": "当前内核空间占用CPU百分比"
    }
   ]
  },
  {
   "title": "用户空间占用CPU百分比",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "aliyun_acs_ecs_dashboard_cpu_user{instanceId=\"$instanceId\"}",
     "legendFormat": "当前用户空间占用CPU百分比"
    }
   ]
  },
  {
   "title": "内存使用率不含缓存",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "aliyun_acs_ecs_dashboard_memory_usedutilization{instanceId=\"$instanceId\"}"
    }
   ]
  },
  {
   "title": "当前等待IO操作的CPU百分比",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "aliyun_acs_ecs_dashboard_cpu_wait{instanceId=\"$instanceId\"}",
     "legendFormat": "当前等待IO操作的CPU百分比"
    }
   ]
  },
  {
   "title": "其他占用CUP百分比",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "aliyun_acs_ecs_dashboard_cpu_other{instanceId=\"$instanceId\"}",
     "legendFormat": "其他占用CUP百分比"
    }
   ]
  },
  {
   "title": "当前消耗的总CPU百分比",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "aliyun_acs_ecs_dashboard_cpu_total{instanceId=\"$instanceId\"}"
    }
   ]
  },
  {
   "title": "剩余内存百分比",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "aliyun_acs_ecs_dashboard_memory_freeutilization{instanceId=\"$instanceId\"}"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 21, "x": 3, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "aliyun_acs_ecs_dashboard_net_tcpconnection{instanceId=\"$instanceId\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "网络带宽",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "aliyun_acs_ecs_dashboard_IntranetInRate{instanceId=\"$instanceId\"}",
     "legendFormat": "私网流入带宽"
    },
    {
     "expr": "aliyun_acs_ecs_dashboard_IntranetOutRate{instanceId=\"$instanceId\"}",
     "legendFormat": "私网流出带宽"
    },
    {
     "expr": "aliyun_acs_ecs_dashboard_InternetOutRate{instanceId=\"$instanceId\"}",
     "legendFormat": "公网流出带宽"
    },
    {
     "expr": "aliyun_acs_ecs_dashboard_InternetInRate{instanceId=\"$instanceId\"}",
     "legendFormat": "公网流入带宽"
    }
   ]
  },
  {
   "title": "系统磁盘读写",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "aliyun_acs_ecs_dashboard_DiskReadBPS{instanceId=\"$instanceId\"}",
     "legendFormat": "系统磁盘总读BPS"
    },
    {
     "expr": "aliyun_acs_ecs_dashboard_DiskWriteBPS{instanceId=\"$instanceId\"}",
     "legendFormat": "系统磁盘总写BPS"
    }
   ]
  },
  {
   "title": "系统磁盘读写IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "aliyun_acs_ecs_dashboard_DiskReadIOPS{instanceId=\"$instanceId\"}",
     "legendFormat": "系统磁盘读IOPS"
    },
    {
     "expr": "aliyun_acs_ecs_dashboard_DiskWriteIOPS{instanceId=\"$instanceId\"}",
     "legendFormat": "系统磁盘写IOPS"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "aliyun_acs_ecs_dashboard_memory_totalspace{instanceId=\"$instanceId\"}",
     "legendFormat": "总内存"
    },
    {
     "expr": "aliyun_acs_ecs_dashboard_memory_usedspace{instanceId=\"$instanceId\"}",
     "legendFormat": "已使用内存+buffers + cached"
    },
    {
     "expr": "aliyun_acs_ecs_dashboard_memory_actualusedspace{instanceId=\"$instanceId\"}",
     "legendFormat": "用户实际使用内存"
    },
    {
     "expr": "aliyun_acs_ecs_dashboard_memory_freespace{instanceId=\"$instanceId\"}",
     "legendFormat": "剩余总内存"
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "aliyun_acs_ecs_dashboard_load_1m{instanceId=\"$instanceId\"}",
     "legendFormat": "load_1m"
    },
    {
     "expr": "aliyun_acs_ecs_dashboard_load_5m{instanceId=\"$instanceId\"}",
     "legendFormat": "load_5m"
    },
    {
     "expr": "aliyun_acs_ecs_dashboard_load_15m{instanceId=\"$instanceId\"}",
     "legendFormat": "load_15m"
    }
   ]
  },
  {
   "title": "磁盘使用量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "aliyun_acs_ecs_dashboard_diskusage_used{instanceId=\"$instanceId\"}",
     "legendFormat": "磁盘的已用存储空间{{ device }}"
    },
    {
     "expr": "aliyun_acs_ecs_dashboard_diskusage_free{instanceId=\"$instanceId\"}",
     "legendFormat": "磁盘的剩余存储空间{{ device }}"
    },
    {
     "expr": "aliyun_acs_ecs_dashboard_diskusage_total{instanceId=\"$instanceId\"}",
     "legendFormat": "磁盘存储总量{{ device }}"
    },
    {}
   ]
  },
  {
   "title": "磁盘读写",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "aliyun_acs_ecs_dashboard_disk_readbytes{instanceId=\"$instanceId\"}",
     "legendFormat": "磁盘每秒读取的字节数{{device}}"
    },
    {
     "expr": "aliyun_acs_ecs_dashboard_disk_writebytes{instanceId=\"$instanceId\"}",
     "legendFormat": "磁盘每秒写入的字节数{{device}}"
    }
   ]
  },
  {
   "title": "磁盘每秒的读写请求数量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "aliyun_acs_ecs_dashboard_disk_readiops{instanceId=\"$instanceId\"}",
     "legendFormat": "磁盘每秒的读请求数量{{device}}"
    },
    {
     "expr": "aliyun_acs_ecs_dashboard_disk_writeiops{instanceId=\"$instanceId\"}",
     "legendFormat": "磁盘每秒的写请求数量{{device}}"
    }
   ]
  },
  {
   "title": "网卡的上下行带宽",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "aliyun_acs_ecs_dashboard_networkin_rate{instanceId=\"$instanceId\"}",
     "legendFormat": "网卡的上行带宽{{device}}"
    },
    {
     "expr": "aliyun_acs_ecs_dashboard_networkout_rate{instanceId=\"$instanceId\"}",
     "legendFormat": "网卡的下行带宽{{device}}"
    }
   ]
  },
  {
   "title": "网卡每秒发送接收数据包",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum by (device) (aliyun_acs_ecs_dashboard_networkin_packages{instanceId=\"$instanceId\"})",
     "legendFormat": "网卡每秒接收的数据包数{{device}}"
    },
    {
     "expr": "sum by (device)  (aliyun_acs_ecs_dashboard_networkout_packages{instanceId=\"$instanceId\"})",
     "legendFormat": "网卡每秒发送的数据包数{{device}}"
    },
    {
     "expr": "sum by (device)  (aliyun_acs_ecs_dashboard_networkin_errorpackages{instanceId=\"$instanceId\"})",
     "legendFormat": "设备驱动器检测到的接收错误包的数量{{device}}"
    },
    {
     "expr": "sum by (device)  (aliyun_acs_ecs_dashboard_networkout_errorpackages{instanceId=\"$instanceId\"})",
     "legendFormat": "设备驱动器检测到的发送错误包的数量{{device}}"
    }
   ]
  }
 ]
}