{
 "title": "Kubernetes / Nodes",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(kube_pod_info,environment)"
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info{environment=~\"$env\"}, cluster)"
   },
   {
    "name": "host_ip",
    "query": "label_values(kube_pod_info{environment=~\"$env\"},host_ip)"
   }
  ]
 },
 "panels": [
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(node_load1{instance=~\"$host_ip:.*\",environment=~\"$env\"})",
     "legendFormat": "load 1m"
    },
    {
     "expr": "max(node_load5{instance=~\"$host_ip:.*\",environment=~\"$env\"})",
     "legendFormat": "load 5m"
    },
    {
     "expr": "max(node_load15{instance=~\"$host_ip:.*\",environment=~\"$env\"})",
     "legendFormat": "load 15m"
    },
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$host_ip:.*\",environment=~\"$env\", mode=\"user\"})",
     "legendFormat": "logical cores"
    }
   ]
  },
  {
   "title": "Usage Per Core",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (cpu) (irate(node_cpu_seconds_total{instance=~\"$host_ip:.*\",environment=~\"$env\", mode!=\"idle\"}[5m]))",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max (sum by (cpu) (irate(node_cpu_seconds_total{instance=~\"$host_ip:.*\",environment=~\"$env\", mode!=\"idle\"}[2m])) ) * 100\n",
     "legendFormat": "{{ cpu }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(sum by (cpu) (irate(node_cpu_seconds_total{instance=~\"$host_ip:.*\",environment=~\"$env\", mode!=\"idle\"}[2m]))) * 100\n"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(\n  node_memory_MemTotal_bytes{instance=~\"$host_ip:.*\",environment=~\"$env\"}\n  - node_memory_MemFree_bytes{instance=~\"$host_ip:.*\",environment=~\"$env\"}\n  - node_memory_Buffers_bytes{instance=~\"$host_ip:.*\",environment=~\"$env\"}\n  - node_memory_Cached_bytes{instance=~\"$host_ip:.*\",environment=~\"$env\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "max(node_memory_Buffers_bytes{instance=~\"$host_ip:.*\",environment=~\"$env\"})",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "max(node_memory_Cached_bytes{instance=~\"$host_ip:.*\",environment=~\"$env\"})",
     "legendFormat": "memory cached"
    },
    {
     "expr": "max(node_memory_MemFree_bytes{instance=~\"$host_ip:.*\",environment=~\"$env\"})",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(\n  (\n    (\n      node_memory_MemTotal_bytes{instance=~\"$host_ip:.*\",environment=~\"$env\"}\n    - node_memory_MemFree_bytes{instance=~\"$host_ip:.*\",environment=~\"$env\"}\n    - node_memory_Buffers_bytes{instance=~\"$host_ip:.*\",environment=~\"$env\"}\n    - node_memory_Cached_bytes{instance=~\"$host_ip:.*\",environment=~\"$env\"}\n    )\n    / node_memory_MemTotal_bytes{instance=~\"$host_ip:.*\",environment=~\"$env\"}\n  ) * 100)\n"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(rate(node_disk_read_bytes_total{instance=~\"$host_ip:.*\",environment=~\"$env\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{instance=~\"$host_ip:.*\",environment=~\"$env\"}[2m]))",
     "legendFormat": "written"
    },
    {
     "expr": "max(rate(node_disk_io_time_seconds_total{instance=~\"$host_ip:.*\",environment=~\"$env\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max by (device) ((node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\",instance=~\"$host_ip:.*\",environment=~\"$env\"}\n        - node_filesystem_avail_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\",instance=~\"$host_ip:.*\",environment=~\"$env\"})\n        / node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\",instance=~\"$host_ip:.*\",environment=~\"$env\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(rate(node_network_receive_bytes_total{instance=~\"$host_ip:.*\",environment=~\"$env\", device!~\"lo\"}[5m]))",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(rate(node_network_transmit_bytes_total{instance=~\"$host_ip:.*\",environment=~\"$env\", device!~\"lo\"}[5m]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Inodes Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(\n  node_filesystem_files{instance=~\"$host_ip:.*\",environment=~\"$env\"}\n  - node_filesystem_files_free{instance=~\"$host_ip:.*\",environment=~\"$env\"}\n)\n",
     "legendFormat": "inodes used"
    },
    {
     "expr": "max(node_filesystem_files_free{instance=~\"$host_ip:.*\",environment=~\"$env\"})",
     "legendFormat": "inodes free"
    }
   ]
  },
  {
   "title": "Inodes Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(\n  (\n    (\n      node_filesystem_files{instance=~\"$host_ip:.*\",environment=~\"$env\"}\n    - node_filesystem_files_free{instance=~\"$host_ip:.*\",environment=~\"$env\"}\n    )\n    / node_filesystem_files{instance=~\"$host_ip:.*\",environment=~\"$env\"}\n  ) * 100)\n"
    }
   ]
  }
 ]
}