{
 "title": "MySQL Performance Schema Details",
 "tags": [
  "MySQL",
  "Percona"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(mysql_up,environment)"
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "label_values(mysql_global_variables_performance_schema{environment=~\"$env\"}, instance)"
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": "label_values(mysql_global_variables_performance_schema{instance=~\"$service_name\"}, instance)"
   },
   {
    "name": "version",
    "label": "Version",
    "query": "label_values(mysql_version_info{instance=~\"$service_name\"},version)"
   },
   {
    "name": "crop_service",
    "label": "Service Name",
    "query": "label_values(mysql_up{instance=~\"$service_name\"}, instance)"
   },
   {
    "name": "crop_host",
    "label": "Crop Node Name",
    "query": "label_values(mysql_up{instance=\"$node_name\"},instance)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, cluster)"
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
   },
   { "name": "schema", "label": "Schema" }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Performance Schema File IO (Events)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, avg by (instance,event_name,mode) (rate(mysql_perf_schema_file_events_total{instance=~\"$service_name\"}[$interval]))>0) or topk(10, avg by (instance,event_name,mode) (irate(mysql_perf_schema_file_events_total{instance=~\"$service_name\"}[5m]))>0)",
     "legendFormat": "{{event_name}} {{mode}}"
    }
   ]
  },
  {
   "title": "Performance Schema File IO (Load)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, avg by (instance,event_name,mode) (rate(mysql_perf_schema_file_events_seconds_total{instance=~\"$service_name\"}[$interval]))>0) or topk(10, avg by (instance,event_name,mode) (irate(mysql_perf_schema_file_events_seconds_total{instance=~\"$service_name\"}[5m]))>0)",
     "legendFormat": "{{event_name}} {{mode}}"
    }
   ]
  },
  {
   "title": "Performance Schema File IO (Bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10, avg by (instance,event_name,mode) (rate(mysql_perf_schema_file_events_bytes_total{instance=~\"$service_name\"}[$interval]))>0) or \ntopk(10, avg by (instance,event_name,mode) (irate(mysql_perf_schema_file_events_bytes_total{instance=~\"$service_name\"}[5m]))>0)",
     "legendFormat": "{{event_name}} {{mode}}"
    }
   ]
  },
  {
   "title": "Performance Schema Waits (Events)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, avg by (instance,event_name) (rate(mysql_perf_schema_events_waits_total{instance=~\"$service_name\"}[$interval]))>0) or topk(5, avg by (instance,event_name) (irate(mysql_perf_schema_events_waits_total{instance=~\"$service_name\"}[5m]))>0)",
     "legendFormat": "{{event_name}} "
    }
   ]
  },
  {
   "title": "Performance Schema Waits (Load)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, avg by (instance,event_name) (rate(mysql_perf_schema_events_waits_seconds_total{instance=~\"$service_name\",event_name!='idle',event_name!='wait/io/table/sql/handler'}[$interval]))>0) or topk(5, avg by (instance,event_name) (irate(mysql_perf_schema_events_waits_seconds_total{instance=~\"$service_name\",event_name!='idle',event_name!='wait/io/table/sql/handler'}[5m]))>0)",
     "legendFormat": "{{event_name}} "
    }
   ]
  },
  {
   "title": "MySQL Index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Index Access Operations (Load)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, avg by (instance,name,operation,schema) (rate(mysql_perf_schema_index_io_waits_seconds_total{instance=~\"$service_name\"}[$interval]))>0) or topk(5, avg by (instance,name,operation,schema) (irate(mysql_perf_schema_index_io_waits_seconds_total{instance=~\"$service_name\"}[5m]))>0)",
       "legendFormat": "{{operation}} {{index}} {{schema}}.{{name}}"
      }
     ]
    },
    {
     "title": "Table Access Operations (Load)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, avg by (instance,name,operation,schema) (rate(mysql_perf_schema_table_io_waits_seconds_total{instance=~\"$service_name\"}[$interval]))>0) or topk(10, avg by (instance,name,operation,schema) (irate(mysql_perf_schema_table_io_waits_seconds_total{instance=~\"$service_name\"}[5m]))>0)",
       "legendFormat": "{{operation}} {{schema}}.{{name}}"
      }
     ]
    },
    {
     "title": "Performance Schema SQL & External Locks (Events)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " topk(10, avg by (instance,operation,schema) (rate(mysql_perf_schema_sql_lock_waits_total{instance=~\"$service_name\"}[$interval]))) or topk(10, avg by (instance,operation,schema) (irate(mysql_perf_schema_sql_lock_waits_total{instance=~\"$service_name\"}[5m])))",
       "legendFormat": "SQL Lock Waits {{ schema }}.{{ operation }}"
      },
      {
       "expr": "topk(10, avg by (instance,operation,schema) (rate(mysql_perf_schema_external_lock_waits_total{instance=~\"$service_name\"}[$interval]))>0) or topk(10, avg by (instance,operation,schema) (irate(mysql_perf_schema_external_lock_waits_total{service_name=~\"$service_name\"}[5m]))>0)",
       "legendFormat": "External Lock Waits {{ schema }}.{{ operation }}"
      }
     ]
    },
    {
     "title": "Performance Schema SQL and External Locks (Seconds)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "mysql_perf_schema_external_lock_waits_seconds_total{instance=~\"$service_name\"}",
       "legendFormat": "External Locks Waits {{ schema }}.{{ name }}.{{ operation }}"
      },
      {
       "expr": "mysql_perf_schema_external_lock_waits_seconds_total{instance=~\"$service_name\"}",
       "legendFormat": "SQL Locks Waits {{ schema }}.{{ name }}.{{ operation }}"
      }
     ]
    }
   ]
  },
  { "title": "MySQL Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "MySQL Uptime",
   "type": "singlestat",
   "description": "**MySQL Uptime**\n\nThe amount of time since the last restart of the MySQL server process.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 44 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (instanceinstance) (mysql_global_status_uptime{instance=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Version",
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 44 },
   "options": {
    "content": "<h5><b><font color=#e68a00><center>$version</center></font></b></h5>\n\n\n"
   }
  },
  {
   "title": "Current QPS",
   "type": "singlestat",
   "description": "**Current QPS**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 44 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (instance) (rate(mysql_global_status_queries{instance=~\"$service_name\"}[$interval]) or irate(mysql_global_status_queries{instance=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "File Handlers Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 44 },
   "format": "percentunit",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(sum(max_over_time(mysql_global_status_open_files{instance=~\"$service_name\"}[$interval])) or sum(max_over_time(mysql_global_status_open_files{instance=~\"$service_name\"}[5m]))) / (sum\r(max_over_time(mysql_global_variables_open_files_limit{instance=~\"$service_name\"}[$interval])) or sum(max_over_time(mysql_global_variables_open_files_limit{instance=~\"$service_name\"}[5m]))\r)"
    }
   ]
  },
  {
   "title": "Table Open Cache Miss Ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 44 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (instance) (1-((rate(mysql_global_status_table_open_cache_hits{instance=~\"$service_name\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{instance=~\"$service_name\"}[5m]))/((rate(mysql_global_status_table_open_cache_hits{instance=~\"$service_name\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{instance=~\"$service_name\"}[5m]))+(rate(mysql_global_status_table_open_cache_misses{instance=~\"$service_name\"}[$interval]) or irate(mysql_global_status_table_open_cache_misses{instance=~\"$service_name\"}[5m])))))"
    }
   ]
  },
  {
   "title": "Table Open Cache Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 44 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (instance) (mysql_global_variables_table_open_cache{instance=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Table Definition Cache Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 44 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (instance) (mysql_global_variables_table_definition_cache{instance=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Service",
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 44 },
   "options": {
    "content": "<h5><b><font color=#e68a00><center><a href=\"/graph/d/mysql-instance-summary/mysql-instance-summary?var-node_name=$node_name&var-service_name=$service_name\" target=\"_blank\">$crop_service...</a></center></font></b></h5>"
   }
  },
  {
   "title": "MySQL Connections",
   "type": "graph",
   "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance) (max(max_over_time(mysql_global_status_threads_connected{instance=~\"$service_name\"}[$interval]) or \nmax_over_time(mysql_global_status_threads_connected{instance=~\"$service_name\"}[5m])))",
     "legendFormat": "Connections"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance) (max_over_time(mysql_global_status_max_used_connections{instance=~\"$service_name\"}[$interval]) or \nmax_over_time(mysql_global_status_max_used_connections{instance=~\"$service_name\"}[5m]))",
     "legendFormat": "Max Used Connections"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance) (max_over_time(mysql_global_variables_max_connections{instance=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_variables_max_connections{instance=~\"$service_name\"}[5m]))",
     "legendFormat": "Max Connections"
    }
   ]
  },
  {
   "title": "MySQL Client Thread Activity",
   "type": "graph",
   "description": "**MySQL Active Threads**\n\nThreads Connected is the number of open connections, while Threads Running is the number of threads not sleeping.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance) (max_over_time(mysql_global_status_threads_connected{instance=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_connected{instance=~\"$service_name\"}[5m]))",
     "legendFormat": "Peak Threads Connected"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance) (max_over_time(mysql_global_status_threads_running{instance=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_running{instance=~\"$service_name\"}[5m]))",
     "legendFormat": "Peak Threads Running"
    },
    {
     "expr": "avg by (instance) (avg_over_time(mysql_global_status_threads_running{instance=~\"$service_name\"}[$interval]) or \navg_over_time(mysql_global_status_threads_running{instance=~\"$service_name\"}[5m]))",
     "legendFormat": "Avg Threads Running"
    }
   ]
  },
  {
   "title": "MySQL Handlers",
   "type": "graph",
   "description": "**MySQL Handlers**\n\nHandler statistics are internal statistics on how MySQL is selecting, updating, inserting, and modifying rows, tables, and indexes.\n\nThis is in fact the layer between the Storage Engine and MySQL.\n\n* `read_rnd_next` is incremented when the server performs a full table scan and this is a counter you don't really want to see with a high value.\n* `read_key` is incremented when a read is done with an index.\n* `read_next` is incremented when the storage engine is asked to 'read the next index entry'. A high value means a lot of index scans are being done.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance,handler) (rate(mysql_global_status_handlers_total{instance=~\"$service_name\"}[$interval]) or \nirate(mysql_global_status_handlers_total{instance=~\"$service_name\"}[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Top Command Counters",
   "type": "graph",
   "description": "**Top Command Counters**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(10, avg by (instance,command) (rate(mysql_global_status_commands_total{instance=~\"$service_name\"}[$interval]))>0 or \navg by (instance,command) (irate(mysql_global_status_commands_total{instance=~\"$service_name\"}[5m]))>0)",
     "legendFormat": "Com_{{ command }}"
    }
   ]
  },
  {
   "title": "Process States",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance,state) (max_over_time(mysql_info_schema_threads{instance=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_info_schema_threads{instance=~\"$service_name\"}[5m]))",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "MySQL Network Traffic",
   "type": "graph",
   "description": "**MySQL Network Traffic**\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance) (rate(mysql_global_status_bytes_received{instance=~\"$service_name\"}[$interval]) or \nirate(mysql_global_status_bytes_received{instance=~\"$service_name\"}[5m]))",
     "legendFormat": "Inbound"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance) (rate(mysql_global_status_bytes_sent{instance=~\"$service_name\"}[$interval]) or \nirate(mysql_global_status_bytes_sent{instance=~\"$service_name\"}[5m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  { "title": "Node Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 71 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (instance) ((node_time_seconds{instance=~\"$node_name:.*\"} - node_boot_time_seconds{instance=~\"$node_name:.*\"}) or (time() - node_boot_time_seconds{instance=~\"$node_name:.*\"}))"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 71 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (instance) (avg_over_time(node_load1{instance=~\"$node_name:.*\"}[$interval]) or avg_over_time(node_load1{instance=~\"$node_name:.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 71 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (instance) (node_memory_MemTotal_bytes{instance=~\"$node_name:.*\"})"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "singlestat",
   "description": "Percent of Memory Available\nNote: on Modern Linux Kernels amount of Memory Available for application is not the same as Free+Cached+Buffers",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 71 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (instance) ((node_memory_MemAvailable_bytes{instance=~\"$node_name:.*\"} or (node_memory_MemFree_bytes{instance=~\"$node_name:.*\"} + node_memory_Buffers_bytes{instance=~\"$node_name:.*\"} + node_memory_Cached_bytes{instance=~\"$node_name:.*\"})) / node_memory_MemTotal_bytes{instance=~\"$node_name:.*\"} * 100)"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "singlestat",
   "description": "RAM + SWAP",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 71 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (instance) (node_memory_MemTotal_bytes{instance=~\"$node_name:.*\"}+node_memory_SwapTotal_bytes{instance=~\"$node_name:.*\"})"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "singlestat",
   "description": "Sum of disk space on all partitions. Note  it can be significantly over-reported in some installations",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 71 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (instance) (sum(avg(node_filesystem_size_bytes{instance=~\"$node_name:.*\",fstype=~\"(ext.|xfs|vfat|)\"}) without (mountpoint)) without (device,fstype))"
    }
   ]
  },
  {
   "title": "Min Space Available",
   "type": "singlestat",
   "description": "Lowest percent of the disk space available",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 71 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(node_filesystem_free_bytes{instance=~\"$node_name:.*\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"}/node_filesystem_size_bytes{instance=~\"$node_name:.*\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"})*100"
    }
   ]
  },
  {
   "title": "Node",
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 71 },
   "options": {
    "content": "<h5><b><font color=#e68a00><center><a href=\"/graph/d/node-instance-summary/node-summary?var-node_name=$node_name\" target=\"_blank\">$crop_host...</a></center></font></b></h5>"
   },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_innodb_buffer_pool_size{instance=~\"$node_name:.*\"} "
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (instance,mode) (clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"$node_name:.*\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"$node_name:.*\",mode!=\"idle\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{instance=~\"$node_name:.*\", mode!=\"total\", mode!=\"idle\"}[$interval]) or avg_over_time(node_cpu_average{instance=~\"$node_name:.*\", mode!=\"total\", mode!=\"idle\"}[5m]))),100))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "CPU Saturation and Max Core Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "avg by (instance) ((avg_over_time(node_procs_running{instance=~\"$node_name:.*\"}[$interval])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", instance=~\"$node_name:.*\"})) or (avg_over_time(node_procs_running{instance=~\"$node_name:.*\"}[5m])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", instance=~\"$node_name:.*\"})))",
     "legendFormat": "Normalized CPU Load"
    },
    {
     "calculatedInterval": "2s",
     "expr": "avg by (instance) (clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"$node_name:.*\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"$node_name:.*\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1))",
     "legendFormat": "Max CPU Core Utilization"
    }
   ]
  },
  {
   "title": "Disk I/O and Swap Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "Bps", "label": "Page Out (-) / Page In (+)" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "avg by (instance) (rate(node_vmstat_pgpgin{instance=~\"$node_name:.*\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=~\"$node_name:.*\"}[5m]) * 1024)",
     "legendFormat": "Disk Reads (Page In)"
    },
    {
     "calculatedInterval": "2s",
     "expr": "avg by (instance) ((rate(node_vmstat_pgpgout{instance=~\"$node_name:.*\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=~\"$node_name:.*\"}[5m]) * 1024))",
     "legendFormat": "Disk Writes (Page Out)"
    },
    {
     "expr": "avg by (instance) ((rate(node_vmstat_pgpgin{instance=~\"$node_name:.*\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=~\"$node_name:.*\"}[5m]) * 1024 ) + (rate(node_vmstat_pgpgout{instance=~\"$node_name:.*\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=~\"$node_name:.*\"}[5m]) * 1024))",
     "legendFormat": "Total"
    },
    {
     "expr": "avg by (instance) (rate(node_vmstat_pswpin{instance=~\"$node_name:.*\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{instance=~\"$node_name:.*\"}[5m]) * 4096)",
     "legendFormat": "Swap In (Reads)"
    },
    {
     "expr": "avg by (instance) (rate(node_vmstat_pswpout{instance=~\"$node_name:.*\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{instance=~\"$node_name:.*\"}[5m]) * 4096)",
     "legendFormat": "Swap Out (Writes)"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "Bps", "label": "Outbound (-) / Inbound (+)" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "avg by (instance) (sum(rate(node_network_receive_bytes_total{instance=~\"$node_name:.*\", device!=\"lo\"}[$interval])) or sum(irate(node_network_receive_bytes_total{instance=~\"$node_name:.*\", device!=\"lo\"}[5m])) or sum(max_over_time(rdsosmetrics_network_rx{instance=~\"$node_name:.*\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_rx{instance=~\"$node_name:.*\"}[5m])))",
     "legendFormat": "Inbound"
    },
    {
     "calculatedInterval": "2s",
     "expr": "avg by (instance) (sum(rate(node_network_transmit_bytes_total{instance=~\"$node_name:.*\", device!=\"lo\"}[$interval])) or sum(irate(node_network_transmit_bytes_total{instance=~\"$node_name:.*\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{instance=~\"$node_name:.*\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_tx{instance=~\"$node_name:.*\"}[5m])))",
     "legendFormat": "Outbound"
    }
   ]
  }
 ]
}