{
 "title": "Prometheus AlertManager",
 "description": "The dashborad using Prometheus AlertManager datasource 0.0.6 version.",
 "tags": [ "0.0.1" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "datasource",
    "query": "camptocamp-prometheus-alertmanager-datasource"
   },
   { "name": "environment", "label": "environment", "query": "label_values(environment)" }
  ]
 },
 "panels": [
  {
   "title": "All alerts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "labelSelector": "*", "target": "Query", "type": "timeserie" }
   ]
  },
  {
   "title": " NodeDiskUseage > 90%",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertname=~\"NodeDiskUseage\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Down Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"NodeDown\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "High Memory Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"NodeMemoryUsageTooHigh95%\"\n",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "High CPU Node",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"NodeCPUUsage95%\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "MySQLReplicationNotRunning",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"MySQLReplicationNotRunning\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "告警发送统计",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\",environment=\"$environment\"})",
     "legendFormat": "发送告警"
    },
    {
     "expr": "count(ALERTS{alertstate=\"pending\",environment=\"$environment\"})",
     "legendFormat": "挂起告警"
    }
   ]
  },
  {
   "title": "All Alerts Info",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "labelSelector": "alertname,severity,description,message,service_name,namespace,pod",
     "target": "Query",
     "type": "table"
    }
   ]
  }
 ]
}