{
 "title": "阿里云资源使用量",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(aliyun_meta_ecs_info{job=\"aliyun-exporter\"}, instance)"
   },
   {
    "name": "HostName",
    "query": "label_values(aliyun_meta_ecs_info{instance=\"$instance\"},HostName)"
   }
  ]
 },
 "panels": [
  {
   "title": "平台总空闲CPU百分比",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_cpu_idle{instance=\"$instance\"})",
     "legendFormat": "当前空闲CPU百分比"
    }
   ]
  },
  {
   "title": "总CPU百分比",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_CPUUtilization{instance=\"$instance\"})",
     "legendFormat": "总CPU百分比"
    }
   ]
  },
  {
   "title": "平台总内核空间占用CPU百分比",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_cpu_system{instance=\"$instance\"})",
     "legendFormat": "当前内核空间占用CPU百分比"
    }
   ]
  },
  {
   "title": "平台总的用户空间占用CPU百分比",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_cpu_user{instance=\"$instance\"})",
     "legendFormat": "当前用户空间占用CPU百分比"
    }
   ]
  },
  {
   "title": "平台硬盘总的使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_diskusage_utilization{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "平台总当前等待IO操作的CPU百分比",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_cpu_wait{instance=\"$instance\"})",
     "legendFormat": "当前等待IO操作的CPU百分比"
    }
   ]
  },
  {
   "title": "平台总其他占用CUP百分比",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_cpu_other{instance=\"$instance\"})",
     "legendFormat": "其他占用CUP百分比"
    }
   ]
  },
  {
   "title": "专有网络公网流出带宽使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_VPC_PublicIP_InternetOutRate_Percent{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "平台总当前消耗的总CPU百分比",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_cpu_total{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "平台总 剩余内存百分比",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_memory_freeutilization{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "平台总内存使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_memory_usedutilization{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "平台总inode使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_fs_inodeutilization{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (state)  (aliyun_acs_ecs_dashboard_net_tcpconnection{instance=\"$instance\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "平台总的网络带宽",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_IntranetInRate{instance=\"$instance\"})",
     "legendFormat": "私网流入带宽"
    },
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_IntranetOutRate{instance=\"$instance\"})",
     "legendFormat": "私网流出带宽"
    },
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_InternetOutRate{instance=\"$instance\"})",
     "legendFormat": "公网流出带宽"
    },
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_InternetInRate{instance=\"$instance\"})",
     "legendFormat": "公网流入带宽"
    },
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_VPC_PublicIP_InternetInRate{instance=\"$instance\"})",
     "legendFormat": "专有网络公网流入带宽"
    },
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_VPC_PublicIP_InternetOutRate{instance=\"$instance\"})",
     "legendFormat": "专有网络公网流出带宽"
    }
   ]
  },
  {
   "title": "系统磁盘总读写",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_DiskReadBPS{instance=\"$instance\"})",
     "legendFormat": "系统磁盘总读BPS"
    },
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_DiskWriteBPS{instance=\"$instance\"})",
     "legendFormat": "系统磁盘总写BPS"
    }
   ]
  },
  {
   "title": "系统磁盘读写IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_DiskReadIOPS{instance=\"$instance\"})",
     "legendFormat": "系统磁盘读IOPS"
    },
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_DiskWriteIOPS{instance=\"$instance\"})",
     "legendFormat": "系统磁盘写IOPS"
    }
   ]
  },
  {
   "title": "平台总内存",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_memory_totalspace{instance=\"$instance\"})",
     "legendFormat": "平台总内存"
    },
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_memory_usedspace{instance=\"$instance\"})",
     "legendFormat": "平台已使用内存+buffers + cached"
    },
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_memory_actualusedspace{instance=\"$instance\"})",
     "legendFormat": "平台用户实际使用内存"
    },
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_memory_freespace{instance=\"$instance\"})",
     "legendFormat": "平台剩余总内存"
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_load_1m{instance=\"$instance\"})",
     "legendFormat": "load_1m"
    },
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_load_5m{instance=\"$instance\"})",
     "legendFormat": "load_5m"
    },
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_load_15m{instance=\"$instance\"})",
     "legendFormat": "load_15m"
    }
   ]
  },
  {
   "title": "磁盘使用量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_diskusage_used{instance=\"$instance\"})",
     "legendFormat": "磁盘的已用存储空间"
    },
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_diskusage_free{instance=\"$instance\"})",
     "legendFormat": "磁盘的剩余存储空间"
    },
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_diskusage_total{instance=\"$instance\"})",
     "legendFormat": "磁盘存储总量"
    },
    {}
   ]
  },
  {
   "title": "平台总磁盘读写",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_disk_readbytes{instance=\"$instance\"})",
     "legendFormat": "平台总磁盘每秒读取的字节数"
    },
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_disk_writebytes{instance=\"$instance\"})",
     "legendFormat": "平台总磁盘每秒写入的字节数"
    }
   ]
  },
  {
   "title": "磁盘每秒的读写请求数量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_disk_readiops{instance=\"$instance\"})",
     "legendFormat": "平台磁盘每秒的读请求数量"
    },
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_disk_writeiops{instance=\"$instance\"})",
     "legendFormat": "平台磁盘每秒的写请求数量"
    }
   ]
  },
  {
   "title": "网卡的上下行带宽",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_networkin_rate{instance=\"$instance\"})",
     "legendFormat": "网卡的上行带宽"
    },
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_networkout_rate{instance=\"$instance\"})",
     "legendFormat": "网卡的下行带宽"
    }
   ]
  },
  {
   "title": "网卡每秒发送接收数据包",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_networkin_packages{instance=\"$instance\"})",
     "legendFormat": "网卡每秒接收的数据包数"
    },
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_networkout_packages{instance=\"$instance\"})",
     "legendFormat": "网卡每秒发送的数据包数"
    },
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_networkin_errorpackages{instance=\"$instance\"})",
     "legendFormat": "设备驱动器检测到的接收错误包的数量"
    },
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_networkout_errorpackages{instance=\"$instance\"})",
     "legendFormat": "设备驱动器检测到的发送错误包的数量"
    }
   ]
  }
 ]
}